### ISSUE TITLE
Gradle: split config into multi-project build

### ISSUE THREAD

**Issue by cagix** [Dungeon-CampusMinden/Dungeon#1323]
Wir haben drei Teilprojekte: [`game`](game) und [`dungeon`](dungeon) sowie [`blockly`](blockly), die alle gemeinsam mit einem **zentralen** [`build.gradle`](build.gradle) gesteuert werden. In [`gradle.properties`](gradle.properties) werden noch irgendwelche Einstellungen vorgenommen, die aber scheinbar veraltet sind. [`settings.gradle`](settings.gradle) gibt es, wird aber irgendwie nicht benutzt.

Ziel ist es, einen ["Multi-Project Build"](https://docs.gradle.org/current/userguide/intro_multi_project_builds.html) aufzubauen und in jedem Teilprojekt eine eigene `build.gradle` mit jeweils relevanten Einstellungen und Targets zu haben. Dabei hängt `dungeon` von `game` ab, dito vermutlich(!) `blockly` von `dungeon`.

Zusätzlich sollten relevante Versionen o.ä. möglichst übergreifend definiert werden ([`gradle.properties`](https://docs.gradle.org/current/userguide/build_environment.html#sec:gradle_configuration_properties) und/oder [`settings.gradle`](https://docs.gradle.org/current/userguide/organizing_gradle_projects.html#sec:settings_file)).

Mittelfristig soll das Teilprojekt `game` per `git subtree` in ein separates Repo exportiert werden können, welches den Studierenden als Vorgabe/Ausgangspunkt zur Verfügung gestellt wird. Dabei müsste noch einmal bzgl. der Einstellungen und Versionen nachgedacht werden - eine zentrale Definition spart erstmal Arbeit, wird aber beim `git subtree` nicht übertragen. Allerdings würde der ganze Gradle-Wrapper auch nicht mit übertragen, da ja nur der Ordner von `game` exportiert wird ... 

siehe auch https://docs.gradle.org/current/userguide/directory_layout.html#dir:project_root und https://docs.gradle.org/current/userguide/organizing_gradle_projects.html

Edit: vorher sollte #1317 gelöst sein.

**Comment by fwatermann** [comment]
@cagix ich hab hier gerade mal reingeschaut. Ich könnte mir vorstellen, dass es schwierig wird da Subprojekte draus zu machen. Aktuell gibt es in `game` dependencies nach `dungeon` und umgekehrt natürlich auch.

**Comment by cagix** [comment]
@fwatermann auweia. mist. 

abhängigkeiten von `dungeon` nach `game` und von `blockly` nach `dungeon` hatte ich erwartet, das müsste doch eigentlich gehen (oder hab ich da irgendwas übersehen?). 

aber das `game` doch noch abhängigkeiten nach `dungeon` hat, ist grad unerwartet. das sollte so nicht vorkommen. wo hast du das denn konkret gefunden?

**Comment by fwatermann** [comment]
Das sind so weit ich das sehen kann "nur" Annotations... Wobei ich nicht weiß, ob die noch benötigt werden, oder nur ein Relikt sind. 

Müssten `VelocityComponent` und `PositionComponent` sein.

**Comment by cagix** [comment]
> Das sind so weit ich das sehen kann "nur" Annotations... Wobei ich nicht weiß, ob die noch benötigt werden, oder nur ein Relikt sind.
> 
> Müssten `VelocityComponent`, `PositionComponent` und `Entity` sein.

hmmmpf. das ist für die dsl. deshalb sind die im `dungeon`-projekt definiert.

aber vermutlich sollten die dann doch im `game` definiert werden - wenn es im selben package bleibt, passt das beim zusammenbauen von `game` und `dungeon` dann wieder.

@AMatutat was ist deine einschätzung?

**Comment by AMatutat** [comment]
> @AMatutat was ist deine einschätzung?

exactly that. Die Annotations-Definition aus Dungeon nach Game ziehen. 

Wollte ich damals schon machen, hatten wir uns irgendwie gegen entschieden.

**Comment by cagix** [comment]
> > @AMatutat was ist deine einschätzung?
> 
> exactly that. Die Annotations-Definition aus Dungeon nach Game ziehen.
> 
> Wollte ich damals schon machen, hatten wir uns irgendwie gegen entschieden.

danke!

ich vermute, damals wollten wir die packages "pure" halten, d.h. nix aus der dsl in die basispackages. aber letztlich hilft das nicht, wenn es doch abhängigkeiten gibt und man die projekte dann nicht trennen kann.

**Comment by fwatermann** [comment]
So wie das gerade ausschaut muss das komplette `dsl` Package und `antlr` dann in das `game` Projekt. Dann ist, außer wenn der move `game/contrib -> dungeon/contrib` (#1314) fertig ist, das `dungeon` Projekt so gut wie leer.

**Comment by cagix** [comment]
> @cagix So wie das gerade ausschaut muss das komplette `dsl` Package und `antlr` dann in das `game` Projekt. Dann ist, außer wenn der move `game/contrib -> dungeon/contrib` (#1314) fertig ist, das `dungeon` Projekt so gut wie leer.

wenn sich das bewahrheiten sollte, hmmm. dann forke ich mir das `game` raus und arbeite damit weiter und der rest darf dann hier in ruhe vergammeln. mist!

**Comment by cagix** [comment]
@fwatermann dann probiere doch mal bitte, die kompletten dsl-annotationen in ein eigenes projekt auszulagern. in den annotationen müsstest du aus `{@link TypeBuilder}` dann `{@link dsl.semanticanalysis.typesystem.typebuilding.TypeBuilder}` machen. vorschlag für den projektnamen wäre "dsl", und für das package "dsl.annotation".

@AMatutat macht das sinn aus deiner sicht?

**Comment by AMatutat** [comment]
> @fwatermann dann probiere doch mal bitte, die kompletten dsl-annotationen in ein eigenes projekt auszulagern. in den annotationen müsstest du aus `{@link TypeBuilder}` dann `{@link dsl.semanticanalysis.typesystem.typebuilding.TypeBuilder}` machen. vorschlag für den projektnamen wäre "dsl", und für das package "dsl.annotation".
> 
> @AMatutat macht das sinn aus deiner sicht?

Hast du dann nicht die Abhängigkeit nur über Eck? `game` funktioniert dann nur mit deinem neuen Projekt, und das neue Projekt nur mit `dungeon`.

Vielleicht bin ich jetzt etwas naiv, aber wenn das Problem die Links in der Javadoc sind, ersetze sie doch. Entweder mit einem Link auf die `/doc` oder halt auf den Code (letzteres hat so seine Probleme, ich weiß). Aber das ist doch alles viel sinnvoller, als hier jetzt eine seltsame Struktur reinzuziehen, nur um die Javadoc-Links beizubehalten.

**Comment by cagix** [comment]
> > @fwatermann dann probiere doch mal bitte, die kompletten dsl-annotationen in ein eigenes projekt auszulagern. in den annotationen müsstest du aus `{@link TypeBuilder}` dann `{@link dsl.semanticanalysis.typesystem.typebuilding.TypeBuilder}` machen. vorschlag für den projektnamen wäre "dsl", und für das package "dsl.annotation".
> > @AMatutat macht das sinn aus deiner sicht?
> 
> Hast du dann nicht die Abhängigkeit nur über Eck? `game` funktioniert dann nur mit deinem neuen Projekt, und das neue Projekt nur mit `dungeon`.

hmmm. wir hätten nochmal ein neues projekt nur für die annotationen. aber dieses hängt selbst von nix ab. `game` benutzt die annotationen (zumindest einige davon), und `dungeon` benutzt die annotationen (vermutlich alle) und zusätzlich `game` ...

alternativ könnte man vermutlich die annotationen auch direkt in `game` integrieren, weil von `game` eh alles andere abhängt. 

wenn wir den spaß direkt nach `game` schieben, sparen wir uns ein weiteres projekt und damit die suche nach einem vernünftigem namen :) ... aber wir tainten `game` dann mit diesen annotationen, wobei das ja via deren flächiger nutzung eh schon passiert ist.

> 
> Vielleicht bin ich jetzt etwas naiv, aber wenn das Problem die Links in der Javadoc sind, ersetze sie doch. Entweder mit einem Link auf die `/doc` oder halt auf den Code (letzteres hat so seine Probleme, ich weiß). Aber das ist doch alles viel sinnvoller, als hier jetzt eine seltsame Struktur reinzuziehen, nur um die Javadoc-Links beizubehalten.

die sache mit dem link in der javadoc der annotationen auf klassen in `dungeon` ist in beiden varianten (extra projekt für die annotationen vs. annotationen in das `game`-projekt integrieren) ein problem, weil man zwar keinen import braucht (wenn man den kompletten package-pfad angibt), aber zum auflösen braucht javadoc eben doch immer die klassen aus dem `dungeon`-projekt - spätestens hier hört es dann auf. wenn ich stattdessen auf `doc/` oder direkt auf die sourcen verlinke, wird das nicht besser: diese links gehen ja auch wieder nach `dungeon`. insofern wäre die robuste lösung, den link auf die `dungeon`-klassen einfach zu entfernen, vermutlich die beste lösung dafür.

**Comment by fwatermann** [comment]
@cagix also soll ich das DSL-Projekt wieder rausschmeißen und die Annotations in `game` schieben?

**Comment by cagix** [comment]
> @cagix also soll ich das DSL-Projekt wieder rausschmeißen und die Annotations in `game` schieben?

was sind die vor- und nachteile für das verschieben nach game?

vorteil:
- kein extra projekt nur für die annotationen (kein neuer name nötig)

nachteil:
- game enthält annotationsdefinitionen, die die studis verwirren könnten 

@fwatermann @AMatutat seht ihr noch mehr?

ansonsten ist es technisch egal - game hängt von den annotationen ab und der rest jeweils von game, oder? und den link im javadoc der annotationen müssen wir für die separierung in beiden varianten entfernen.

**Comment by AMatutat** [comment]
Jetzt mal ins Unreine gedacht:

Könnte ich nicht alle Klassen, die die Annotationen haben, ins `dungeon` "kopieren"? 
Also so etwas wie `dungeon.Entity extends game.Entity`. 
`game.Entity` ist dann "clean", also ohne Annotationen, und `dungeon.Entity` ist eigentlich nur eine Kopie/Erweiterung um die DSL-Annotationen.

Vorteile:
* Ganz klare Trennung
* DSL-Typen werden etwas unabhängiger vom Game-Typen

Nachteile:
* Schon eine Form von Duplikaten im Code

**Comment by cagix** [comment]
> Jetzt mal ins Unreine gedacht:
> 
> Könnte ich nicht alle Klassen, die die Annotationen haben, ins `dungeon` "kopieren"? Also so etwas wie `dungeon.Entity extends game.Entity`. `game.Entity` ist dann "clean", also ohne Annotationen, und `dungeon.Entity` ist eigentlich nur eine Kopie/Erweiterung um die DSL-Annotationen.
> 
> Vorteile:
> 
> * Ganz klare Trennung
> * DSL-Typen werden etwas unabhängiger vom Game-Typen
> 
> Nachteile:
> 
> * Schon eine Form von Duplikaten im Code

@AMatutat Hmmm. Würde das nicht am Ende das Kopieren von ca. 80..90% des Codes aus `Game` nach `Dungeon` bedeuten? Wenn ich das richtig sehe, sind die Annotationen an fast jeder Klasse dran. Das wäre dann gleichzeitig das Ende von `Game` - wenn es Änderungen in `Dungeon` gibt, müssten die dann auch noch nach `Game` kopiert werden ... Andererseits könnte ich in `Game` dann tatsächlich alle Annotationen rauswerfen und damit den Zweitsemestlern das Leben etwas leichter machen. Aber vielleicht tangiert die das mit den Annotationen auch maximal periphär? Wer weiss.

Oder verstehe ich Deinen Vorschlag grad falsch?

**Comment by AMatutat** [comment]
> Edit: Oh. Ich habe das mit der Ableitung übersehen. Würde das bzgl. der DSL überhaupt so funktionieren? Wenn das gehen würde, wäre Game "pure" und komplett unabhängig vom ganzen DSL-Spaß. Andererseits wäre Dungeon immer noch abhängig von Game (dort sind ja die Basisklassen drin), und wir hätten schon einige Strukturen mehr oder weniger doppelt.


Die Abhängigkeit von Dungeon nach Game wirst du ja immer haben, außer du machst wirklich zwei separate Projekte raus. Das hat wieder Vor- und Nachteile die man evaluieren könnte. 

On mein Vorschlag mit der DSL so Funktioniert..... I dont know. @malt-r könnte da vermutlich was schlaueres sagen. Nach meinen Verständnis sollte das aber (mit anpassungen) Möglich sein.
