### ISSUE TITLE
Doc: Keine Leer- und Sonderzeichen in den Pfaden

### ISSUE THREAD

**Issue by mpeters4** [Dungeon-CampusMinden/Dungeon#1325]
Bitte in die **Anleitung** aufnehmen, dass unter Windows Fehler beim starten des Dungeons auftreten, wenn in den Pfaden Leer- oder Sonderzeichen auftauchen.

Fehlermeldung: Exception in thread "main" java.lang.IllegalArgumentException: URI is not hierarchical

---

**Nur Dokumentation (Game, Dungeon) ergänzen!** Für eine Analyse/Fix gibt es #1361.

**Comment by tgrothe** [comment]
Das könnte mit
`new File(resourceUrl.toURI());`
zu tun haben, was ersetzt werden könnte/sollte durch
`<...>.class.getClassLoader().getResourceAsStream("<...>");`
siehe auch [hier](https://stackoverflow.com/questions/10144210/java-jar-file-use-resource-errors-uri-is-not-hierarchical).

Ich hab mal danach gesucht, wo das auftritt:

![grafik](https://github.com/Programmiermethoden/Dungeon/assets/85501570/ae63da51-35bd-4bf6-8d73-627682cef56b)

Vielleicht hilft das.

**Comment by tgrothe** [comment]
... Bzw. [toExternalForm()](https://docs.oracle.com/javase/8/docs/api/java/net/URL.html#toExternalForm--) anstatt `toURI()` wäre richtiger, denn dann sollten keine Pfadprobleme mehr auftreten, imho.

**Comment by cagix** [comment]
@mpeters4 i want to believe?
