### ISSUE TITLE
Dungeon: Einfacheres Starten des Starter.jar

### ISSUE THREAD

**Issue by mpeters4** [Dungeon-CampusMinden/Dungeon#1326]
Die Starter.jar könnte beim Start den Ordner nach ".dng" Dateien durchsuchen und diese zur Auswahl anbieten. 
So wird der Start über die Kommandozeile mit entsprechendem Argument erspart und durch einen einfachen Doppelklick ermöglicht. 

Dies könnte die Anwendung von Menschen erleichtern, die nicht so viel Erfahrung mit dem Umgang von Computern haben wie wir Informatiker.

**Comment by cagix** [comment]
**Umsetzung**: 

1. Falls eine `.dng`-Datei beim Start angegeben wurde (ala `java -jar Starter.jar --args "MY_FILE.dng"`), dann soll diese geladen werden und kein Filechooser angezeigt werden. 
2. Anderenfalls soll direkt nach dem Start (`main()`) ein `JFileChooser`-Dialog aufgemacht werden mit dem aktuellen Ordner als Startordner und einem Dateinamen-Filter auf `.dng` - hierüber muss der User dann eine passende Konfiguration auswählen. Die wird dann über den aktuellen Mechanismus eingelesen.

**Comment by tgrothe** [comment]
Kann ich das machen?

**Comment by cagix** [comment]
> Kann ich das machen?

@tgrothe das ist ein open-source-projekt, hier kann jeder, der möchte, pull-requests stellen :)

**Comment by AMatutat** [comment]
> Anderenfalls soll direkt nach dem Start (main()) ein JFileChooser-Dialog aufgemacht werden [...]

Das hatte ich mal mit Swing probiert, darauf kam libGDX nicht wirklich klar (es ist danach eingefroren). Ich erinnere mich daran, gelesen zu haben, dass das an der Schnittstelle liegt, die die beiden verwenden.

Ich weiß nicht mehr, ob ich das damals vor der Game-Loop oder aus der Game-Loop raus aufgerufen habe...

**Comment by tgrothe** [comment]
https://github.com/Programmiermethoden/Dungeon/blob/master/dungeon/doc/readme.md#starten-des-dungeon-systems

gibt es zufällig ein "predefined dmg file" im repo? oder könnte ein solches generiert werden?

**Comment by cagix** [comment]
> > Anderenfalls soll direkt nach dem Start (main()) ein JFileChooser-Dialog aufgemacht werden [...]
> 
> Das hatte ich mal mit Swing probiert, darauf kam libGDX nicht wirklich klar (es ist danach eingefroren). Ich erinnere mich daran, gelesen zu haben, dass das an der Schnittstelle liegt, die die beiden verwenden.
> 
> Ich weiß nicht mehr, ob ich das damals vor der Game-Loop oder aus der Game-Loop raus aufgerufen habe...
> 
> Edit: [#882 (comment)](https://github.com/Programmiermethoden/Dungeon/issues/882#issuecomment-1647889636)

@AMatutat Ja, und ich hatte sogar zugestimmt mit dem Bild im Hinterkopf, dass @bcg7 die Enduserin ist. Aber nun wollen ja doch auch andere mitspielen, und trotz Fachhintergrund ist @mpeters4 gestolpert. D.h. wir sollten perspektivisch hier doch nochmal dran.

Meine Idee wäre, dass man die Sache mit dem `FileChooser` erledigt, **bevor** irgendwas mit libGDX passiert, also insbesondere deutlich bevor man in die Loop springt. Eventuell braucht man einen "Loader", also ein kleines extra "Programm", was dann nur die Abfrage der DNG-Datei macht und dann damit eine CMD-Zeile für den eigentlichen Start des Programms zusammen klöppelt und das dann im Hintergrund ausführen lässt?

**Comment by tgrothe** [comment]
Wäre es nicht auch sinnvoll, es würde erst eine Art Anleitungsfenster angezeigt werden, wenn keine `.dng`-Datei via `args`-Argument angegeben ist bzw. vergessen wurde? Also, bevor das Auswahlfenster erscheint.

**Comment by cagix** [comment]
> Wäre es nicht auch sinnvoll, es würde erst eine Art Anleitungsfenster angezeigt werden, wenn keine `.dng`-Datei via `args`-Argument angegeben ist bzw. vergessen wurde? Also, bevor das Auswahlfenster erscheint.

jain :) 

ein hinweis ist sinnvoll, aber ein extra popup erinnert mich an die usability von win7 🤔 kann nicht ein entsprechender hinweis im filechooser-dialog eingebaut werden? manche widgets haben so eine möglichkeit ...

**Comment by tgrothe** [comment]
> > Wäre es nicht auch sinnvoll, es würde erst eine Art Anleitungsfenster angezeigt werden, wenn keine `.dng`-Datei via `args`-Argument angegeben ist bzw. vergessen wurde? Also, bevor das Auswahlfenster erscheint.
> 
> jain :) 
> 
> ein hinweis ist sinnvoll, aber ein extra popup erinnert mich an die usability von win7 🤔 kann nicht ein entsprechender hinweis im filechooser-dialog eingebaut werden? manche widgets haben so eine möglichkeit ...

Win7 ftw 🤣

Nein, leider nicht. Das file chooser Fenster ist modal, d. h. die ganze Anwendung wird blockiert, und es ist nur sehr begrenzt anpassbar... Oder wir müssten den file chooser komplett selbst bauen, und das möchte glaube ich keiner...

Aber ich schaue trotzdem mal, inwiefern anpassbar...
