### ISSUE TITLE
Fehler in "task definition.md"

### ISSUE THREAD

**Issue by mpeters4** [Dungeon-CampusMinden/Dungeon#1342]
Mir ist ein Fehler in der task definition aufgefallen. Das Beispiel zu Zuordnungsaufgaben beginnt mit "multiple_choice_task" an und muss "assign_task" lauten.

Die Datei liegt unter https://github.com/Programmiermethoden/Dungeon/blob/Demo/dungeon/doc/dsl/task_definition.md

Edit: fix URL

**Comment by mpeters4** [comment]
Soeben ist mir aufgefallen, dass sich dieser Fehler auch durch die gesamte Befehlstabelle zieht.

**Comment by cagix** [comment]
@mpeters4 danke für die meldung. wenn du magst, kannst du gern einen pr zum fixen einkippen :) ... 

was meinst du mit "... zieht sich durch die gesamte befehlstabelle"?

**Comment by mpeters4** [comment]
@cagix Sorry für die ungenaue Beschreibung. Ich war auf dem Sprung. 

Unter dem Kapitel "Beschreibung der Eigenschaften" befinden sich in der Tabelle bei der "grading_function" und dem "scenario_builder" auch noch Begriffe, die mit multiple_choice benannt sind. Da weiß ich allerdings nicht ob das ein Fehler ist, oder Absicht. 

Ich bin hier nicht mitwirkend und habe das Projekt auch nicht auf. Daher kein PR meinerseits :)

**Comment by cagix** [comment]
> @cagix Sorry für die ungenaue Beschreibung. Ich war auf dem Sprung.
> 
> Unter dem Kapitel "Beschreibung der Eigenschaften" befinden sich in der Tabelle bei der "grading_function" und dem "scenario_builder" auch noch Begriffe, die mit multiple_choice benannt sind. Da weiß ich allerdings nicht ob das ein Fehler ist, oder Absicht.
> 
> Ich bin hier nicht mitwirkend und habe das Projekt auch nicht auf. Daher kein PR meinerseits :)

hmmm, in den sourcen gibt es einen [`AssignTask.java `](https://github.com/Programmiermethoden/Dungeon/blob/Demo/dungeon/src/task/tasktype/AssignTask.java) und ein [`Quiz.java `](https://github.com/Programmiermethoden/Dungeon/blob/Demo/dungeon/src/task/tasktype/Quiz.java). Letzteres wird nochmal abgeleitet/spezialisiert für single choice und multiple choice, d.h. deine vermutung scheint mir korrekt zu sein.
