### ISSUE TITLE
CI: Warning in Windows runner

### ISSUE THREAD

**Issue by cagix** [Dungeon-CampusMinden/Dungeon#1354]
When executing the `build` task on `windows-latest`, there is a warning during post setup of JDK21. Our `./gradlew assemble` however runs fine ... 

Is this a glitch in the windows runner or the `setup-java` action (both from GitHub)?

 
<img width="1310" alt="Screenshot 2024-01-22 at 18 18 07" src="https://github.com/Programmiermethoden/Dungeon/assets/20356276/206d4353-656b-420d-8263-87a4ccd73988">

**Comment by tgrothe** [comment]
Das scheint "sporadisch" aufzutreten, siehe hier https://github.com/gradle/gradle-build-action/issues/644

**Comment by cagix** [comment]
> Das scheint "sporadisch" aufzutreten, siehe hier [gradle/gradle-build-action#644](https://github.com/gradle/gradle-build-action/issues/644)

@tgrothe Wenn ich Deinen Link richtig lese, ist "sporadisch" nicht das korrekte Wort. Das Problem scheint am Caching zu liegen. Brauchen wir das hier überhaupt in unseren Workflows?

**Comment by tgrothe** [comment]
> Brauchen wir das hier überhaupt in unseren Workflows?

@cagix Vermutlich nicht. Der Cache des Gradle-Plugins soll(!) den Workflow/die CI nur etwas beschleunigen.
