### ISSUE TITLE
FileHandling: IllegalArgumentException: URI is not hierarchical

### ISSUE THREAD

**Issue by AMatutat** [Dungeon-CampusMinden/Dungeon#1409]
Ich hab mir meine Demo (Jar + DSL-Files) in mein ICloud-Drive Verzeichnis gespeichert und beim Ausführen von 
`java -XstartOnFirstThread -jar Demo.jar --args "demo.dng"` gabs eine Exception.
` 

<details> <summary> Exception </summary>

```
[LWJGL] [ThreadLocalUtil] Unsupported JNI version detected, this may result in a crash. Please inform LWJGL developers.
Exception in thread "main" java.lang.IllegalArgumentException: URI is not hierarchical
	at java.base/java.io.File.<init>(File.java:420)
	at core.components.DrawComponent.loadAnimationsFromIDE(DrawComponent.java:448)
	at core.components.DrawComponent.loadAnimationAssets(DrawComponent.java:355)
	at core.components.DrawComponent.<init>(DrawComponent.java:86)
	at contrib.entities.HeroFactory.newHero(HeroFactory.java:58)
	at contrib.entities.EntityFactory.newHero(EntityFactory.java:39)
	at starter.DemoStarter.createHero(DemoStarter.java:187)
	at starter.DemoStarter.lambda$taskSelectorOnSetup$10(DemoStarter.java:147)
	at core.game.GameLoop.setup(GameLoop.java:184)
	at core.game.GameLoop.render(GameLoop.java:154)
	at com.badlogic.gdx.Game.render(Game.java:48)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:387)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:192)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:166)
	at core.game.GameLoop.run(GameLoop.java:105)
	at core.Game.run(Game.java:57)
	at starter.DemoStarter.main(DemoStarter.java:122)
```
</details>

Ist vermutlich irgendein schräger Edge-Case, ich wollte ihn aber einfach mal festhalten.
Meine Demo-Version ist auch etwas älter, aber da sich seit dem nicht viel getan hat....

**Comment by cagix** [comment]
duplikat von #1361

**Comment by tgrothe** [comment]
> in mein ICloud-Drive Verzeichnis gespeichert

fun fact/side note: Mit dem "virtuellen" OneDrive Verzeichnis geht es ;) (das hat kein ümläüts im Pfad...)

**Comment by cagix** [comment]
> > in mein ICloud-Drive Verzeichnis gespeichert
> 
> fun fact/side note: Mit dem "virtuellen" OneDrive Verzeichnis geht es ;) (das hat kein ümläüts im Pfad...)

das war sicher "nur" ein leerzeichen irgendwo. aber vielleicht war ich mit dem closen des issues auch etwas vorschnell.

@AMatutat Du hast den Befehl oben (`java -jar ...`) sicher in der Shell eingegeben. Kannst Du bitte den Pfad mal posten (einfach `pwd` an der selben Stelle ausführen), damit wir sicher sagen können, ob das wg. der Leerzeichen ist? 

In #1366 gibt es auch einen Lösungsvorschlag, wobei ich da noch kein Bild habe, ob der wirklich das Problem löst oder nur für die beiden erwähnten Klassen.

**Comment by tgrothe** [comment]
@cagix Ich weiß, das wäre eine suboptimale Vorgehensweise, aber können wir #1366 nicht erst einmal "übernehmen" und dann "warten", ob es noch Fehler gibt?

**Comment by cagix** [comment]
> @cagix Ich weiß, das wäre eine suboptimale Vorgehensweise, aber können wir #1366 nicht erst einmal "übernehmen" und dann "warten", ob es noch Fehler gibt?

@tgrothe nein. ich möchte das problem verstehen, und ich möchte deine lösung verstehen und prüfen, ob beides zusammen passt. da ist damals(tm) jede menge überlegung reingegangen, die leider nicht dokumentiert wurde und die leider auch immer wieder an verschiedenen stellen neu gemacht bzw. erfunden wurde. ich möchte von diesem bruchstückhaften vorgehen gern wegkommen. sobald du eine erklärung lieferst, was das konzept hinter deiner lösung in #1366 ist und warum das das problem lösen könnte, können wir da weiter machen.

@AMatutat dein input wäre wirklich sehr willkommen - dein baby ist schon ganz heiser!

**Comment by AMatutat** [comment]
Leerzeichen Detected....
`/Users/andre/Library/Mobile Documents/com~apple~CloudDocs/Dungeon-Projekte/questing_demo`

**Comment by AMatutat** [comment]
> @AMatutat dein input wäre wirklich sehr willkommen - dein baby ist schon ganz heiser!

Daycare ist auch nicht mehr das was es mal war.

**Comment by tgrothe** [comment]
> Leerzeichen Detected.... `/Users/andre/Library/Mobile Documents/com~apple~CloudDocs/Dungeon-Projekte/questing_demo`

Bei mir

```
$ pwd
/c/Users/tobi/OneDrive/dungeon
```

> > @cagix Ich weiß, das wäre eine suboptimale Vorgehensweise, aber können wir #1366 nicht erst einmal "übernehmen" und dann "warten", ob es noch Fehler gibt?
> 
> @tgrothe nein. ich möchte das problem verstehen, und ich möchte deine lösung verstehen und prüfen, ob beides zusammen passt. da ist damals(tm) jede menge überlegung reingegangen, die leider nicht dokumentiert wurde und die leider auch immer wieder an verschiedenen stellen neu gemacht bzw. erfunden wurde. ich möchte von diesem bruchstückhaften vorgehen gern wegkommen. sobald du eine erklärung lieferst, was das konzept hinter deiner lösung in #1366 ist und warum das das problem lösen könnte, können wir da weiter machen.

ich hatte doch schon versucht, den Lösungsansatz zu beschreiben

wir brauchen die Fallunterscheidung, weil wir a) das Verzeichnis durchsuchen möchten (die Resources) und b) nicht auf LibGdx `FileHandle` zurückgreifen möchten

besser kann ich es nicht beschreiben

**Comment by cagix** [comment]
> Leerzeichen Detected.... `/Users/andre/Library/Mobile Documents/com~apple~CloudDocs/Dungeon-Projekte/questing_demo`

OK, da ist (a) ein Leerzeichen und (b) zweimal Tilde drin. Leerzeichen sind #1361, Tilde weiss ich nicht - sollte man dort auch mit aufnehmen. Dann kann das hier als Duplikat zu.

**Comment by cagix** [comment]
>  > > @cagix Ich weiß, das wäre eine suboptimale Vorgehensweise, aber können wir #1366 nicht erst einmal "übernehmen" und dann "warten", ob es noch Fehler gibt?
> > 
> > 
> > @tgrothe nein. ich möchte das problem verstehen, und ich möchte deine lösung verstehen und prüfen, ob beides zusammen passt. da ist damals(tm) jede menge überlegung reingegangen, die leider nicht dokumentiert wurde und die leider auch immer wieder an verschiedenen stellen neu gemacht bzw. erfunden wurde. ich möchte von diesem bruchstückhaften vorgehen gern wegkommen. sobald du eine erklärung lieferst, was das konzept hinter deiner lösung in #1366 ist und warum das das problem lösen könnte, können wir da weiter machen.
> 
> ich hatte doch schon versucht, den Lösungsansatz zu beschreiben
> 
> wir brauchen die Fallunterscheidung, weil wir a) das Verzeichnis durchsuchen möchten (die Resources) und b) nicht auf LibGdx `FileHandle` zurückgreifen möchten

Vielleicht steht bei mir grad was auf dem Schlauch ... Ich habe verstanden, dass wir eine Fallunterscheidung brauchen zw. JAR und local FS. Was ich noch nicht verstehe: Wer ist (außer den beiden Klassen, die für die aufgetretene Exception verantwortlich waren) noch alles beteiligt? Welche Arten von Umgang mit dem Dateisystem werden im Dungeon verwendet? Im Proposal in #1366 wird per Fallunterscheidung geschaut, wo man ist - aber dann wird ein String zurückgeliefert, aus dem die aufrufende Stelle dann wieder einen Pfad(??) oder ein File(??) oder was auch genau macht (Erklärung fehlt) und den Kram dann einliest - muss ich dort dann nicht auch wieder eine Fallunterscheidung machen? Wie funktioniert die Fallunterscheidung? Ist das ein sicherer Weg? Gibt es Alternativen, wie würden die aussehen? Gibt es irgendwelche Randbedingungen, die noch beachtet werden müssen?

**Comment by cagix** [comment]
> > Leerzeichen Detected.... `/Users/andre/Library/Mobile Documents/com~apple~CloudDocs/Dungeon-Projekte/questing_demo`
> 
> OK, da ist (a) ein Leerzeichen und (b) zweimal Tilde drin. Leerzeichen sind #1361, Tilde weiss ich nicht - sollte man dort auch mit aufnehmen. Dann kann das hier als Duplikat zu.

Habe sowohl #1361 als auch #1366 um die Tilde ergänzt, damit ist das Thema dort abgedeckt und hier kann als Duplikat zu.

**Comment by tgrothe** [comment]
> > > > @cagix Ich weiß, das wäre eine suboptimale Vorgehensweise, aber können wir #1366 nicht erst einmal "übernehmen" und dann "warten", ob es noch Fehler gibt?
> > > 
> > > 
> > > @tgrothe nein. ich möchte das problem verstehen, und ich möchte deine lösung verstehen und prüfen, ob beides zusammen passt. da ist damals(tm) jede menge überlegung reingegangen, die leider nicht dokumentiert wurde und die leider auch immer wieder an verschiedenen stellen neu gemacht bzw. erfunden wurde. ich möchte von diesem bruchstückhaften vorgehen gern wegkommen. sobald du eine erklärung lieferst, was das konzept hinter deiner lösung in #1366 ist und warum das das problem lösen könnte, können wir da weiter machen.
> > 
> > 
> > ich hatte doch schon versucht, den Lösungsansatz zu beschreiben
> > wir brauchen die Fallunterscheidung, weil wir a) das Verzeichnis durchsuchen möchten (die Resources) und b) nicht auf LibGdx `FileHandle` zurückgreifen möchten
> 
> Vielleicht steht bei mir grad was auf dem Schlauch ... Ich habe verstanden, dass wir eine Fallunterscheidung brauchen zw. JAR und local FS. Was ich noch nicht verstehe: Wer ist (außer den beiden Klassen, die für die aufgetretene Exception verantwortlich waren) noch alles beteiligt? Welche Arten von Umgang mit dem Dateisystem werden im Dungeon verwendet? Im Proposal in #1366 wird per Fallunterscheidung geschaut, wo man ist - aber dann wird ein String zurückgeliefert, aus dem die aufrufende Stelle dann wieder einen Pfad(??) oder ein File(??) oder was auch genau macht (Erklärung fehlt) und den Kram dann einliest - muss ich dort dann nicht auch wieder eine Fallunterscheidung machen? Wie funktioniert die Fallunterscheidung? Ist das ein sicherer Weg? Gibt es Alternativen, wie würden die aussehen? Gibt es irgendwelche Randbedingungen, die noch beachtet werden müssen?

Der eigentliche Mechanismus zum Laden der Animationen funktioniert ja (also mit absoluten Pfaden zum Asset). Also müssen wir nur schauen, an welchen Stellen das Verzeichnis durchsucht werden soll. Und das ist AFAIK nur in diesen beiden Klassen so. Das heißt, zusätzliche Randbedingungen gibt es nicht.
