### ISSUE TITLE
Gradle: Duplicate content root detected

### ISSUE THREAD

**Issue by tgrothe** [Dungeon-CampusMinden/Dungeon#1418]
> Path [.../Dungeon/game/assets] of module [Dungeon_Projekt.dungeon.main] was removed from modules [Dungeon_Projekt.game.main]

Das meldet IJ bei mir und es kam nach der Projektaufteilung in 6d44fa6

**Comment by cagix** [comment]
Ja, das muss wieder raus. Jedes Subprojekt muss seine eigenen Assets haben. Diese Querabhängigkeiten sind Mist.
