### ISSUE TITLE
Task-Selector: Inkonsistente Darstellung

### ISSUE THREAD

**Issue by cagix** [Dungeon-CampusMinden/Dungeon#1420]
Wenn ich den Dungeon per `./gradlew clean :dungeon:runStarter` starte und manuell das DNG-File `dungeon/doc/dsl/examplescripts/example_scenario.dng` selektiere, bekomme ich im Task-Selector tatsächlich die Auswahl "config" angezeigt:

<img width="443" alt="Screenshot 2024-02-17 at 12 05 21" src="https://github.com/Dungeon-CampusMinden/Dungeon/assets/20356276/4af1eb4a-210e-469b-b775-cd98c79cc983">

Wenn ich die DSL-Datei aber direkt beim Start mitgebe (`./gradlew clean :dungeon:runStarter --args=dungeon/doc/dsl/examplescripts/example_scenario.dng`), ist das Fensterchen für den Task-Selector zu klein und ich kann nichts auswählen:

<img width="443" alt="Screenshot 2024-02-17 at 12 04 43" src="https://github.com/Dungeon-CampusMinden/Dungeon/assets/20356276/54f1b307-0c2c-49cb-a520-66d155ae07fb">

Das ist konsistent über mehrere Starts.

**Comment by tgrothe** [comment]
> Wenn ich die DSL-Datei aber direkt beim Start mitgebe (`./gradlew clean :dungeon:runStarter --args=dungeon/doc/dsl/examplescripts/example_scenario.dng`), ist das Fensterchen für den Task-Selector zu klein und ich kann nichts auswählen

AFAIK brauchst du für die args-Option den vollen Pfad (also einen Absolutpfad).

**Comment by cagix** [comment]
> > Wenn ich die DSL-Datei aber direkt beim Start mitgebe (`./gradlew clean :dungeon:runStarter --args=dungeon/doc/dsl/examplescripts/example_scenario.dng`), ist das Fensterchen für den Task-Selector zu klein und ich kann nichts auswählen
> 
> AFAIK brauchst du für die args-Option den vollen Pfad (also einen Absolutpfad).

nö. es startet ja mit der datei.

**Comment by tgrothe** [comment]
> > > Wenn ich die DSL-Datei aber direkt beim Start mitgebe (`./gradlew clean :dungeon:runStarter --args=dungeon/doc/dsl/examplescripts/example_scenario.dng`), ist das Fensterchen für den Task-Selector zu klein und ich kann nichts auswählen
> > 
> > 
> > AFAIK brauchst du für die args-Option den vollen Pfad (also einen Absolutpfad).
> 
> nö. es startet ja mit der datei.

ich glaube, es startet dann nicht mit der datei, aber einem dummy config.

**Comment by cagix** [comment]
> > > > Wenn ich die DSL-Datei aber direkt beim Start mitgebe (`./gradlew clean :dungeon:runStarter --args=dungeon/doc/dsl/examplescripts/example_scenario.dng`), ist das Fensterchen für den Task-Selector zu klein und ich kann nichts auswählen
> > > 
> > > 
> > > AFAIK brauchst du für die args-Option den vollen Pfad (also einen Absolutpfad).
> > 
> > 
> > nö. es startet ja mit der datei.
> 
> ich glaube, es startet dann nicht mit der datei, aber einem dummy config.


OMG. Was für ein 💩 😱

@tgrothe Du liegst mit Deiner Vermutung richtig. ` ./gradlew clean :dungeon:runStarter --args="wuppie"` startet den Mist widerspruchslos und lässt mich dann eben nichts auswählen. Wer programmiert so einen Sch**ß?!

**Comment by tgrothe** [comment]
> > > > > Wenn ich die DSL-Datei aber direkt beim Start mitgebe (`./gradlew clean :dungeon:runStarter --args=dungeon/doc/dsl/examplescripts/example_scenario.dng`), ist das Fensterchen für den Task-Selector zu klein und ich kann nichts auswählen
> > > > 
> > > > 
> > > > AFAIK brauchst du für die args-Option den vollen Pfad (also einen Absolutpfad).
> > > 
> > > 
> > > nö. es startet ja mit der datei.
> > 
> > 
> > ich glaube, es startet dann nicht mit der datei, aber einem dummy config.
> 
> OMG. Was für ein 💩 😱
> 
> @tgrothe Du liegst mit Deiner Vermutung richtig. ` ./gradlew clean :dungeon:runStarter --args="wuppie"` startet den Mist widerspruchslos und lässt mich dann eben nichts auswählen. Wer programmiert so einen Sch**ß?!
> 
> Wozu haben wir dann den Spaß mit dem JFileChooser gemacht? Das kann doch keiner mehr erklären?!

I don't know, aber es lässt sich ja beheben ... ;)

**Comment by cagix** [comment]
Klar. Kann man beheben. Ich habe aber nur endlich viel Zeit. Und ich habe das Gefühl, dass das nur die absolute Spitze vom Eisberg ist.

**Comment by tgrothe** [comment]
> Klar. Kann man beheben. Ich habe aber nur endlich viel Zeit. Und ich habe das Gefühl, dass das nur die absolute Spitze vom Eisberg ist.

Durch die "Umstrukturierung" in Sub-/Teilprojekte kam da eben einiges zum Vorschein. Aber gefühlt funktioniert das meiste ja.
