### ISSUE TITLE
Gradle: fix asset configuration 

### ISSUE THREAD

**Issue by tgrothe** [Dungeon-CampusMinden/Dungeon#1426]
Die Projekte sollen voneinander unabhängige Assets haben. 
- Das Subprojekt `Game` hat eigenständige Assets und zieht keine weiteren von außen an.
- Das Subprojekt `Dungeon` baut auf `Game` auf und hat eigenständige Assets und nutzt ggf. weitere Assets aus `Game`. 
- Das Subprojekt `Blockly` baut auf `Dungeon` auf und hat eigenständige Assets und nutzt ggf. weitere Assets aus `Dungeon`. 

~~Allerdings nutzen dungeon und game teilweise die gleichen Assets.~~

~~Deshalb müssen einige Assets von dungeon nach game kopiert werden und umgekehrt.~~

~~Zudem muss es eine Strategie für den Gradle-Mechanismus geben, dass "doppelte" Assets erlaubt sind.~~

> Eine Möglichkeit wäre, in den gradle builds die sourceSets.main.resources.srcDirs anzupassen. 

Das war ja schon drin, und nachdem ich tatsächlich fehlende Assets (in Dungeon-Klassen hard gecoded) nachträglich im Subprojekt aufgenommen hatte, schien mir der Eintrag in der Dungeon-build.gradle nicht mehr nötig. Das war offensichtlich vorschnell.

Eine kurzfristige Lösung wäre, diese Konfiguration wieder einzubauen.

Mittelfristig muss man aber schauen, wie das "richtig" geht. Ich habe das Gefühl, dass in Dungeon gar nicht die .classes aus Game genutzt werden, sondern dass hier das Game.jar verwendet wird. Und dann stolpert natürlich die fummelige Erkennung. Vermutlich müssten einfach nur beim :dungeon:assemble die classes und Assets aus Game/build/ nach Dungeon/build/kopiert werden.

**Comment by cagix** [comment]
@tgrothe Wenn Du schon ein Ticket aufmachst, an dem Du offenbar arbeitest, kannst Du das Ticket dann auch bitte an Dich assignen?

**Comment by tgrothe** [comment]
> @tgrothe Wenn Du schon ein Ticket aufmachst, an dem Du offenbar arbeitest, kannst Du das Ticket dann auch bitte an Dich assignen?

ja, merke ich mir für nächste mal. :)

**Comment by cagix** [comment]
> Allerdings nutzen dungeon und game teilweise die gleichen Assets.

@tgrothe welche sind das genau

**Comment by cagix** [comment]
> Deshalb müssen einige Assets von dungeon nach game kopiert werden und umgekehrt.

@tgrothe Nein. Es muss eine entsprechende Gradle-Konfiguration eingerichtet werden, so dass in Dungeon auch die Assets aus Game verfügbar sind.

**Comment by cagix** [comment]
Wenn das nicht gelingt, muss zur Not darüber nachgedacht werden, den Plan mit der Aufteilung in separate Subprojekte wieder aufzugeben und den Kram einfach wieder in einen großen Klumpen zusammen zu führen.

Vorher muss aber klar sein, dass Gradle und/oder libGDX das nicht unterstützen.

@tgrothe Ich rede von "nachdenken", nicht von experimentellen PR.

**Comment by tgrothe** [comment]
> > Allerdings nutzen dungeon und game teilweise die gleichen Assets.
> 
> @tgrothe welche sind das genau

Viele, ich würde sagen, ca. 50 %.

Ich müsste dafür erst eine genaue Liste erstellen.

**Comment by tgrothe** [comment]
> > Deshalb müssen einige Assets von dungeon nach game kopiert werden und umgekehrt.
> 
> @tgrothe Nein. Es muss eine entsprechende Gradle-Konfiguration eingerichtet werden, so dass in Dungeon auch die Assets aus Game verfügbar sind.

Eine Möglichkeit wäre, in den gradle builds die `sourceSets.main.resources.srcDirs` anzupassen. Aber dann entstünden "Querabhängigkeiten" bzw. meckert dann IJ wieder, dass es "multiple content roots" gibt.

**Comment by cagix** [comment]
Ehrlich: Die Meinung von IJ geht mir soooo nah am Knie vorbei! Wichtig ist, dass das Buildtool damit klar kommt.

**Comment by tgrothe** [comment]
> Ehrlich: Die Meinung von IJ geht mir soooo nah am Knie vorbei! Wichtig ist, dass das Buildtool damit klar kommt.

Na gut, dann da wieder hereinpfriemeln. Ich aber heute nicht mehr.

**Comment by cagix** [comment]
> > > Allerdings nutzen dungeon und game teilweise die gleichen Assets.
> 
> > 
> 
> > @tgrothe welche sind das genau
> 
> 
> 
> Viele, ich würde sagen, ca. 50 %.
> 

Zeige mir bitte im Code, wer wo was verwendet. 

In Game ist fast nichts an Funktionalität, wer soll denn da was aus Dungeon haben wollen?

Und die Klassen in Dungeon haben ihre Assets dort definiert.

Das Einzige, was nicht klappt, ist das Auflösen der Pfade. Wenn Du den Starter in Dungeon startest, holt der sich seine Assets aus Dungeon. Aber gleichzeitig sind dann auch Klassen aus Game beteiligt, die ihre Assets dann nicht (mehr) finden. 

Das ist aber schlicht ein Konfigurationsproblem (für die Klassen haben wir es ja auch bereits hinbekommen). Und das haben andere Projekte auch schon gehabt und vermutlich gelöst. Kopieren aller Assets ist jedenfalls KEINE Lösung!

**Comment by cagix** [comment]
> > Ehrlich: Die Meinung von IJ geht mir soooo nah am Knie vorbei! Wichtig ist, dass das Buildtool damit klar kommt.
> 
> 
> 
> Na gut, dann da wieder hereinpfriemeln. Ich aber heute nicht mehr.

Kein Grund, sauer zu werden. Es verlangt ja auch keiner von Dir! 

Nur blockiere mir bitte nicht meine Zeit mit "Lösungen", die keine sind. Der ganze Tag war heute ein recht unangenehmes und unproduktives Immer-wieder-Erklären, ohne dass ich das Gefühl habe, dass das ich damit durch komme.

**Comment by tgrothe** [comment]
> > > > Allerdings nutzen dungeon und game teilweise die gleichen Assets.
> > 
> > 
> > > 
> > 
> > 
> > > @tgrothe welche sind das genau
> > 
> > 
> > Viele, ich würde sagen, ca. 50 %.
> 
> Zeige mir bitte im Code, wer wo was verwendet.

Es "kracht" in dieser Methode:

https://github.com/Dungeon-CampusMinden/Dungeon/blob/730ef32bde0664907f95f5f03d074b83c5fa629a/game/src/core/components/DrawComponent.java#L352-L381

Wenn du eine Ausgabe des `IPath` am Anfang machst, kannst du sehen, welche das sind bzw. welche nicht gefunden werden können.

> Kein Grund, sauer zu werden. Es verlangt ja auch keiner von Dir!

Ich bin nicht sauer oder beleidigt o. Ä.

Und ich fand nicht, dass heute alles nur Zeitvergeudung gewesen ist. Aber ggf. haben wir da unterschiedliche Ansichten, aber das ist ok.

**Comment by cagix** [comment]
> > > > > Allerdings nutzen dungeon und game teilweise die gleichen Assets.
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > @tgrothe welche sind das genau
> 
> > > 
> 
> > > 
> 
> > > Viele, ich würde sagen, ca. 50 %.
> 
> > 
> 
> > Zeige mir bitte im Code, wer wo was verwendet.
> 
> 
> 
> Es "kracht" in dieser Methode:
> 
> 
> 
> https://github.com/Dungeon-CampusMinden/Dungeon/blob/730ef32bde0664907f95f5f03d074b83c5fa629a/game/src/core/components/DrawComponent.java#L352-L381
> 
> 
> 
> Wenn du eine Ausgabe des `IPath` am Anfang machst, kannst du sehen, welche das sind bzw. welche nicht gefunden werden können.
> 

Ja, das ist exakt eine Manifestation dessen, was ich oben schrieb: In Dungeon werden (natürlich) Klassen aus Game verwendet. Der nötige Classpath wird in den Gradle-Skripten definiert.

Aber unsere aktuelle Gradle-Konfiguration schafft das nicht für die Assets - hier muss das analog zum Classpath eben auch noch erreicht werden.



> 
> Und ich fand nicht, dass heute alles nur Zeitvergeudung gewesen ist. Aber ggf. haben wir da unterschiedliche Ansichten, aber das ist ok.

Wie viele Male sollte ich mir heute was anschauen/reviewen? Wie viele Kommentare musste ich schreiben? Wie oft ging es immer wieder hartnäckig um das Kopieren von Assests? Und sind wir der Lösung auch nur einen Schritt näher gekommen?

**Comment by cagix** [comment]
> Eine Möglichkeit wäre, in den gradle builds die sourceSets.main.resources.srcDirs anzupassen. 

Das war ja schon drin, und nachdem ich tatsächlich fehlende Assets (in Dungeon-Klassen hard gecoded) nachträglich im Subprojekt aufgenommen hatte, schien mir der Eintrag in der Dungeon-build.gradle nicht mehr nötig. Das war offensichtlich vorschnell.

Eine kurzfristige Lösung wäre, diese Konfiguration wieder einzubauen.

Mittelfristig muss man aber schauen, wie das "richtig" geht. Ich habe das Gefühl, dass in Dungeon gar nicht die .classes aus Game genutzt werden, sondern dass hier das Game.jar verwendet wird. Und dann stolpert natürlich die fummelige Erkennung. Vermutlich müssten einfach nur beim :dungeon:assemble die classes under Assets aus Game/build/ nach Dungeon/build/kopiert werden.

**Comment by tgrothe** [comment]
Imho, brauchen wir in Blockly noch ein `sourceSets.main.resources.srcDirs += '../dungeon/assets'`, da durch `implementation project(':dungeon')` anscheinend die resource source dirs nicht mitkommen (nur die Implementierung kommt mit).

**Comment by cagix** [comment]
> Imho, brauchen wir in Blockly noch ein `sourceSets.main.resources.srcDirs += '../dungeon/assets'`, da durch `implementation project(':dungeon')` anscheinend die resource source dirs nicht mitkommen (nur die Implementierung kommt mit).
> 
> ... zum Vergleich, in Dungeon nutzen wir `api`.

Bei `api` scheinen die Ressourcen aber auch nicht korrekt mitzukommen, das ist doch der ganze Ärger grad. Letztlich geht es darum, ob und wie die referenzierten Sourcen genutzt werden sollen. 

Ich hatte oben schon mal geschrieben, dass es vermutlich eine Idee wäre, `assemble` zu ergänzen um das Kopieren von Ressourcen? Aber vielleicht auch nicht. 

Wenn Du die `resources.srcDirs` erweiterst, dann nimm bitte die Gradle-Schreibweise mit `project(...)...`. Ich will nicht später bei Änderungen wieder überall dran müssen, nur weil dann Pfade nicht mehr stimmen.

**Comment by tgrothe** [comment]
> Wenn Du die `resources.srcDirs` erweiterst, dann nimm bitte die Gradle-Schreibweise mit `project(...)...`. Ich will nicht später bei Änderungen wieder überall dran müssen, nur weil dann Pfade nicht mehr stimmen.

Das hatte ich auch so, aber anscheinend funktioniert es dann nicht, weil das ja eine ganze Liste ist.

**Comment by cagix** [comment]
> > Wenn Du die `resources.srcDirs` erweiterst, dann nimm bitte die Gradle-Schreibweise mit `project(...)...`. Ich will nicht später bei Änderungen wieder überall dran müssen, nur weil dann Pfade nicht mehr stimmen.
> 
> Das hatte ich auch so, aber anscheinend funktioniert es dann nicht, weil das ja eine ganze Liste ist.

mach geschweifte klammern um den ausdruck

**Comment by tgrothe** [comment]
> > > Wenn Du die `resources.srcDirs` erweiterst, dann nimm bitte die Gradle-Schreibweise mit `project(...)...`. Ich will nicht später bei Änderungen wieder überall dran müssen, nur weil dann Pfade nicht mehr stimmen.
> > 
> > 
> > Das hatte ich auch so, aber anscheinend funktioniert es dann nicht, weil das ja eine ganze Liste ist.
> 
> mach geschweifte klammern um den ausdruck

danke,

`sourceSets.main.resources.srcDirs += {project(':dungeon').sourceSets.main.resources.srcDirs}`

geht. :D

**Comment by tgrothe** [comment]
@cagix Ich habe mich einfach vertan und glaube, dieses Issue ist inzwischen geklärt, oder? Also könnt hier zu?

**Comment by cagix** [comment]
> @cagix Ich habe mich einfach vertan und glaube, dieses Issue ist inzwischen geklärt, oder? Also könnt hier zu?

du sprichst in rätseln. wieso glaubst du, dass du dich vertan hast? ist das problem, dass man im `dungeon`-subprojekt keine assets aus dem `game`-subprojekt nutzen kann, obwohl dieses die basis für den `dungeon` bildet, mittlerweile gelöst?

**Comment by tgrothe** [comment]
Ich denke(™), die settings.gradle müsste so sein:

```
rootProject.name = 'Dungeon Projekt'

// Include the projects in game, dungeon and blockly
include 'game'
include 'game:dungeon'
include 'game:dungeon:blockly'
```

und dann müsste natürlich auch die Verzeichnisstruktur kaskadiert werden, also dungeon müsste in game liegen und blockly in dungeon,

und dann müssten auch die Tasks (wo)anders definiert/registriert werden,

... und dann würde da keiner mehr "durchblicken".

**Comment by cagix** [comment]
> Ich denke(™), die settings.gradle müsste so sein:
> 
> 
> 
> ```
> 
> rootProject.name = 'Dungeon Projekt'
> 
> 
> 
> // Include the projects in game, dungeon and blockly
> 
> include 'game'
> 
> include 'game:dungeon'
> 
> include 'game:dungeon:blockly'
> 
> ```
> 
> 
> 
> und dann müsste natürlich auch die Verzeichnisstruktur kaskadiert werden, also dungeon müsste in game liegen und blockly in dungeon,
> 
> 
> 
> und dann müssten auch die Tasks (wo)anders definiert/registriert werden,
> 
> 
> 
> ... und dann würde da keiner mehr "durchblicken".

@tgrothe wie kommst du denn da drauf? und was genau sollte die kaskadierung lösen und warum?

das ist doch nur das aktuelle modell und statt nebeneinander liegenden ordnern möchtest du die ineinander schachteln. ich sehe nich, wie das eigentliche problem damit gelöst werden könnte?

**Comment by tgrothe** [comment]
@cagix Dann würde ich vorschlagen, doch `sourceSets.main.resources.srcDirs += {project(':dungeon').sourceSets.main.resources.srcDirs}` in Blockly zu verwenden, weil beim Starten von Blockly die Resources sonst nicht über den classLoader erreichbar sind (womöglich liegen diese dann in einer jar).

Hab aber erst wieder heute Abend Zeit dafür.

**Comment by cagix** [comment]
@tgrothe So, ich habe jetzt mal ein wenig für Dich recherchiert. 

Wie eingangs erwähnt, werden die Ressourcen (Assets) beim Auflösen der Projektabhängigkeiten nicht mitgenommen. Also für `dungeon` fehlen die Assets aus `game`, obwohl dieses Subprojekt eine Dependency für `dungeon` ist. Für die .class-Files ist das kein Problem, weil Gradle hier das Jar-File aus `game` einfach in den Classpath für `dungeon` packt. Die Lösung besteht darin, die Assets aus `game` beim Bearbeiten von `dungeon` in den Build-Path von `dungeon` kopieren zu lassen: [processResources](https://docs.gradle.org/current/dsl/org.gradle.language.jvm.tasks.ProcessResources.html). 

Schau Dir mal die Konfiguration vom Original-Spiel an: https://github.com/cagix/shattered-pixel-dungeon/blob/425c90135d7d666dd1f4715f165dca91a7fb449e/desktop/build.gradle#L9-L12 ... in der `build.gradle` im `desktop`-Subprojekt wird spezifiziert, dass bitte schön die Assets aus den Subprojekten `core` und `desktop` in den Build-Ordner kopiert werden sollen

```
processResources {
    from new File(project(':core').projectDir, "/src/main/assets")
    from new File(project(':desktop').projectDir,"/src/main/assets")
}
```

Ich frage mich, ob das nicht bei uns auch reichen würde:

- Wenn man auf der Konsole oder aus der IDE startet, werden die abhängigen Assets mit kopiert. Damit muss man nicht sowohl im lokalen Filesystem als auch in einer JAR im Classpath nach Assets suchen.
- Wenn man das Starter.jar baut und von dort startet, sind die Assets sowieso drin. Hier muss man dann auch nur im JAR-File suchen.

(Analog auch für `blockly`.)

**Comment by tgrothe** [comment]
> @tgrothe So, ich habe jetzt mal ein wenig für Dich recherchiert.
> 
> Wie eingangs erwähnt, werden die Ressourcen (Assets) beim Auflösen der Projektabhängigkeiten nicht mitgenommen. Also für `dungeon` fehlen die Assets aus `game`, obwohl dieses Subprojekt eine Dependency für `dungeon` ist. Für die .class-Files ist das kein Problem, weil Gradle hier das Jar-File aus `game` einfach in den Classpath für `dungeon` packt. Die Lösung besteht darin, die Assets aus `game` beim Bearbeiten von `dungeon` in den Build-Path von `dungeon` kopieren zu lassen: [processResources](https://docs.gradle.org/current/dsl/org.gradle.language.jvm.tasks.ProcessResources.html).
> 
> Schau Dir mal die Konfiguration vom Original-Spiel an: https://github.com/cagix/shattered-pixel-dungeon/blob/425c90135d7d666dd1f4715f165dca91a7fb449e/desktop/build.gradle#L9-L12 ... in der `build.gradle` im `desktop`-Subprojekt wird spezifiziert, dass bitte schön die Assets aus den Subprojekten `core` und `desktop` in den Build-Ordner kopiert werden sollen
> 
> ```
> processResources {
>     from new File(project(':core').projectDir, "/src/main/assets")
>     from new File(project(':desktop').projectDir,"/src/main/assets")
> }
> ```
> 
> Ich frage mich, ob das nicht bei uns auch reichen würde:
> 
>     * Wenn man auf der Konsole oder aus der IDE startet, werden die abhängigen Assets mit kopiert. Damit muss man nicht sowohl im lokalen Filesystem als auch in einer JAR im Classpath nach Assets suchen.
> 
>     * Wenn man das Starter.jar baut und von dort startet, sind die Assets sowieso drin. Hier muss man dann auch nur im JAR-File suchen.
> 
> 
> (Analog auch für `blockly`.)

Das klingt doch gut. `processResources` in Verbindung mit den Assets hatte ich tatsächlich gar nicht auf dem Schirm gehabt, bzw. dass es so eine Funktion gibt. Dadurch wird dann vermutlich auch einiges in #1366 usw. einfacher werden.

**Comment by cagix** [comment]
@tgrothe Für die Tests würde ich das aber nicht einbauen. Die sollen ja in sich konsistent sein und nur für die Klassen im jeweiligen Subprojekt, d.h. die dürfen per Definition gar keine Abhängigkeiten in andere Subprojekte haben. Oder andersherum: Bei den Tests darf nur im lokalen Filesystem gesucht werden, wenn Assets aufzulösen sind. Dafür reicht aber die normale, bereits vorhandene Konfiguration der Test-Assets in den `build.gralde`.

**Comment by cagix** [comment]
> Dadurch wird dann vermutlich auch einiges in https://github.com/Dungeon-CampusMinden/Dungeon/pull/1366 usw. einfacher werden.

Das versuche ich Dir doch die ganze Zeit zu sagen 🤔

Das Vorgehen in #1366 ersetzt für mich ein "wildes Konstrukt" (vorsichtig ausgedrückt) mit einem noch wilderen Konstrukt, ohne dass wirklich klar ist, was man eigentlich braucht. 

Deshalb hatte ich in #1437 versucht, per Refactoring schrittweise nach einer echten Lösung zu kommen. Okay, ich habe aber auch erst nur den einfachen Fall gelöst, das ganze Fummeln mit den Animationen habe ich mangels Zeit bisher nicht anschauen können. Aber mein Bauchgefühl sagt mir, dass auch hier eine klare und relativ einfache Lösung möglich ist - ohne riesige Visitor-Pattern-Implementierungen und ohne dass man immer in allen nur denkbaren Locations spazieren geht.

**Comment by tgrothe** [comment]
> ohne riesige Visitor-Pattern-Implementierungen

Das fand ich gar nicht mal schlecht, 😩 zumal dieses Pattern ja in zwei Klassen auftaucht. Aber der Rest ist einfach unnötig kompliziert.

**Comment by cagix** [comment]
> > ohne riesige Visitor-Pattern-Implementierungen
> 
> Das fand ich gar nicht mal schlecht, 😩 zumal dieses Pattern ja in zwei Klassen auftaucht. Aber der Rest ist einfach unnötig kompliziert.

ja, es taucht auch in der alten doku von oracle auf (java 8). aber ich denke, es ist hier einfach unnötig komplex und over-engineered. 

über das suchen vorsichtshalber in allen potentiellen locations sind wir uns (hoffentlich) einig - das ist kein gutes vorgehen. aber das sollte ja nun mit der aktuellen asset konfiguration auch erledigt sein.
