### ISSUE TITLE
DSL Dungeon: dungeon:runStarter zurzeit nicht spielbar

### ISSUE THREAD

**Issue by tgrothe** [Dungeon-CampusMinden/Dungeon#1427]
Wenn ich

`./gradlew clean runStarter --args=assets/scripts/example.dng`

aufrufe und dann eine Mission auswähle ("morgens" oder "nachmittags"), stürzt das DSL-Dungeon ab bzw. es startet nicht.

Fehlermeldung: `No .dng file selected. Exiting ...`

Vermutlich liegt das daran, dass einige Assets nicht da sind oder nicht geladen werden können.

Mir ist das nach der Aufteilung der build.gradle zuerst hier aufgefallen: https://github.com/Dungeon-CampusMinden/Dungeon/pull/1366#issuecomment-1948194255 und hier wurde es weiter kommentiert: https://github.com/Dungeon-CampusMinden/Dungeon/pull/1422#issuecomment-1950240496

und in #1422 (#1426) habe ich versucht, das zu beheben, allerdings hätten wir dann doppelte Assets (also die gleichen Assets an zwei unterschiedlichen Stellen).

Ich habe zurzeit keine Idee, wie man das einfach lösen könnte.

**Comment by cagix** [comment]
Duplikat von bzw. abgedeckt durch #1426 und #1428
