### ISSUE TITLE
Fehlerbehandlung in der Starter-main()-Methode anpassen

### ISSUE THREAD

**Issue by tgrothe** [Dungeon-CampusMinden/Dungeon#1428]
Die Fehlerbehandlung in der main()-Methode von https://github.com/Dungeon-CampusMinden/Dungeon/blob/master/dungeon/src/starter/Starter.java sollte noch einmal überarbeitet werden.

Zurzeit kann es passieren, dass zum Beispiel eine Fehlermeldung ausgegeben wird, die aber mit dem eigentlichen Fehler nix zu tun hat, sondern einen anderen Fehlerfall betrifft.

**Comment by cagix** [comment]
Ja, das ist richtig. 

Allerdings hatte ich mich in einer früheren Diskussion dafür entschieden, hier Lesbarkeit vor exaktem try/catch zu bevorzugen.
