### ISSUE TITLE
Dungeon Starter: Adjust exception handling

### ISSUE THREAD

**Issue by cagix** [Dungeon-CampusMinden/Dungeon#1430]
Um die `main()`-Methode des Dungeon-Starters lesbar zu halten, wurde entschieden, ein gemeinsames `try/catch` um alle Statements zu legen (statt wie üblich je potentiell fehlschlagendes Statement ein eigenes `try/catch`). Dadurch wird eine deutlich bessere Lesbarkeit gewährleistet, und man erhält einen zentralen Ausstiegspunkt aus dem Spiel. 

Andererseits wird dadurch teilweise eine falsche Ausgabe als Ausstiegsgrund generiert, wenn beispielsweise tief im Spiel eine `NullPointerException` hochgereicht wird und im `main()` fälschlicherweise dann ausgegeben wird, dass es keine Konfiguration gab.

In https://github.com/Dungeon-CampusMinden/Dungeon/pull/1429#issuecomment-1951272860 wurde die folgende Idee diskutiert, die hier weiterverfolgt werden soll:

> @tgrothe eine idee, über die man vielleicht nochmal näher nachdenken sollte: jede exception bringt ja eine message mit sich. von der wird bisher nirgendwo gebrauch gemacht. aber vielleicht könnte man das sinnvoll nutzen? mir ist ja letztlich im `main()` egal, welcher typ von exception da kommt und von welchem statement die grad ausgelöst wurde - ich kann ja eh nix machen außer das spiel abbrechen. aber ich könnte eine sinnvolle meldung ausgeben, und da könnte man sich evtl. auch die message in der exception nutzen (`e.getMessage()`). das würde freilich auch bedeuten, dass man die dann auch an den entsprechenden stellen setzt.
> 
> und man könnte noch weiter überlegen, ob man nicht aufgetretene exceptions direkt am auftreten fängt und als `throwable` neu verpackt weiter reicht - das würde dann ggf. die myriaden von `xyz() throws bla, blub, wuppie, fluppie, foo, bar` abkürzen. aber auch verstecken, d.h. darüber muss nochmal gründlich nachgedacht werden.

Es ist das Ziel des Tickets, sich Gedanken zu machen. Ich halte nicht viel von eigenen Exception-Klassen (es gibt ja mehr als genug im JDK). Aber vielleicht muss man das hier in diesem konkreten Fall ja auch gar nicht?! Es geht doch nur darum, das Spiel abzubrechen und eine sinnvolle Meldung (statt Stacktrace) auszugeben. D.h. es würde vermutlich völlig reichen, an den verschiedenen Stellen dafür zu sorgen, dass die hochgereichte Exception mit einer sinnvollen Message versehen wird, und im `main()` muss man die im `catch` nur noch ausgeben und dann das Spiel beenden.

**Comment by tgrothe** [comment]
Kann ich das angehen? Ist ja eigentlich keine große Änderung... Dann würde ich mich assigneen.

**Comment by cagix** [comment]
mach doch. ich hab keine zeit dazu.

**Comment by tgrothe** [comment]
test
