### ISSUE TITLE
Dungeon: "missing_texture.png" entfernen

### ISSUE THREAD

**Issue by tgrothe** [Dungeon-CampusMinden/Dungeon#1432]
Es gibt in Game ein Asset `game/assets/animation/missing_texture.png`.

Diese Textur wird immer dann geladen, wenn eine Textur nicht dargestellt werden kann, es also einen Fehler gab.

Dieser Fehler sollte nicht auftreten, aber es ist in seltenen Fällen möglich, dass er doch auftritt. Zurzeit "verschweigen" wir aber dadurch einen Fehlerfall.

Ich möchte diese Textur entfernen und stattdessen eine RuntimeException "werfen", die das Spiel in so einem Fall beendet.

---

Oder übersehe ich hierbei ein didaktisches Konzept?

**Comment by cagix** [comment]
@AMatutat Das assigne ich mal an Dich. Ich sehe für beide Varianten einen Use-Case, kenne aber die Diskussion hinter der aktuellen Variante nicht.
