### ISSUE TITLE
Das Feuerballprojektil sollte nicht leiser sein als die Hintergrundmusik

### ISSUE THREAD

**Issue by tgrothe** [Dungeon-CampusMinden/Dungeon#1480]
Das Feuerballprojektil sollte nicht leiser sein als die Hintergrundmusik. Für mein Lautstärkeempfinden ist das zu leise bzw. zusammen mit den übrigen Geräuschen irritierend.

Follows from the discussion in #1479.

**Comment by Flamtky** [comment]
Imo ist die Musik einfach viel zu laut 😆. So ein Volume Slider wäre schon ganz nett.

**Comment by tgrothe** [comment]
Hmm, ich bin mir nicht sicher, ob die Feuerbälle (bei "Dauerfeuer"...) dann nicht doch nervig wären.

@Flamtky Für den Vol.-Slider mach am besten mal ein eigenes Ticket auf.
