### ISSUE TITLE
Dojo: Level noch einmal umsortieren

### ISSUE THREAD

**Issue by cagix** [Dungeon-CampusMinden/Dungeon#1492]
@tgrothe @Denniso3 Ich bin nun endlich dazu gekommen, den Vorlesungsplan für S24 zu fixieren und die Übungszettel dazu zu schreiben (naja, zumindest einige). Dabei haben sich noch einmal ein paar Probleme gezeigt, die eine Umsortierung von Inhalten nötig gemacht haben :/

Tut mir leid, aber ich brauche doch noch einmal kurzfristig eine Umsortierung der Level: 
1. "Der Vergessene Wald" (ehemals Level 1)
2. "Die Vulkanhöhle" (ehemals Level 4)
3. "Tempel der verlorenen Geheimnisse" (ehemals Level 2)
4. "Kerker des Grauens" (ehemals Level 3)

Oder andersherum gesprochen: 
- Level 1 (alt) bleibt Level 1 (neu)
- Level 4 (alt) wird das neue Level 2
- Level 2 (alt) wird das neue Level 3
- Level 3 (alt) wird das neue Level 4

Bitte auch in der Doku nachziehen.

**Comment by tgrothe** [comment]
@Denniso3 Machst du das (schnell)? Ich bin gerade spazieren. 

Die einzelnen Räume müssen ausgeschnitten und in die richtigen Pakete eingefügt werden. 

Danach müssen die einzelnen Räume noch umbenannt werden und alles weitere nachgezogen werden...

Bin um 17 Uhr wieder Daheim. :)
