### ISSUE TITLE
Dojo: Was genau ist die Aufgabe in Level 1 mit der Datei-Überarbeitung?

### ISSUE THREAD

**Issue by cagix** [Dungeon-CampusMinden/Dungeon#1501]
@tgrothe Was genau möchtest Du da haben in der überarbeiteten Datei `Klasse`? Was genau erwartest Du in der Funktion `redirectOutputTo2`? Das try/catch ist hier nicht mandatory. Und selbst mit try/catch möchtest Du das nicht akzeptieren? Ich verstehe ehrlich gesagt Deine Aufgabe an der Stelle nicht. Der Tip ist nicht wirklich hilfreich - es wird eine lokale Variable definiert und mit diesem String läuft der folgende Code der Methode durch und es wird die gewünschte "8" ausgegeben. Nur wenn Du von hintenrum per Reflection scheinbar irgendwas umstößt, dann klappt das halt nicht - aber das passiert normalerweise ja nicht im Code?!

(Den Syntaxfehler findet IJ automatisch und baut halt überall ein "static" ein.)

Wenn Du Dir die vorgegebene Klasse nochmal anschaust, wirst Du feststellen, dass die Kommentare teilweise nicht mehr zu den verwendeten Namen passen.

Die Hinweise im Popup im Spiel sind auch nicht korrekt. Du startest das Spiel im Projekt-Ordner. Dann ist der Pfad nicht `../dojo-dungeon/todo-assets/Fehler_Syntax/FehlerhafteKlasse.java`, sondern `dojo-dungeon/todo-assets/Fehler_Syntax/FehlerhafteKlasse.java`.

Es wäre gut, wenn die Aufgabe so formuliert wäre, wenn es auch Studis im zweiten Semester klar verstehen: Was soll ich hier machen, was wird von mir erwartet?

**Comment by tgrothe** [comment]
@cagix Bis wann soll das ca. fertig sein?

**Comment by cagix** [comment]
> @cagix Bis wann soll das ca. fertig sein?

ehrliche antwort? vorletzte woche. 

ich habe den dojo jetzt als bonusaufgabe formuliert. dann ist es nicht ganz so dramatisch, wenn die studis nicht wissen, was von ihnen erwartet wird. das blatt ist online, also,je früher das gefixt ist, um so besser.

**Comment by tgrothe** [comment]
> > @cagix Bis wann soll das ca. fertig sein?
> 
> ehrliche antwort? vorletzte woche.
> 
> ich habe den dojo jetzt als bonusaufgabe formuliert. dann ist es nicht ganz so dramatisch, wenn die studis nicht wissen, was von ihnen erwartet wird. das blatt ist online, also,je früher das gefixt ist, um so besser.
> 
> @tgrothe das kind ist jetzt eh im brunnen. also bitte keine nacht- oder wochenendschichten einlegen. nächste woche ist auch noch ne woche.

Ich spare mir mal sarkastische Brunnen-Kommentare, denn es gibt tatsächlich viele verunglückte Kinder; aber ich bin zuversichtlich, bis Anfang oder Mitte nächster Woche sollten wir das hinbekommen haben. :)
