### ISSUE TITLE
Dojo: Level 1, MC-Fragen: Falsche Antworten als korrekt hinterlegt?

### ISSUE THREAD

**Issue by cagix** [Dungeon-CampusMinden/Dungeon#1502]
Ich hab mal die Türen im Code alle aufgemacht, damit ich in den dritten Raum von Level 1 komme.

Die Frage zum Lambda ist nicht korrekt. Das ist afaik kein Interface mit einer Methode, sondern eine namenslose Funktion. Bitte anpassen. 

(Man kann einen Lambda-Ausdruck überall dort _nutzen_, wo ein Funktions-Interface als Typ erwartet wird - aber ein Lambda-Ausdruck **_ist_ kein** Funktions-Interface.)

**Comment by tgrothe** [comment]
@Denniso3 kannst du hier bitte schauen? Bei Fragen, quatsch mich an.

**Comment by tgrothe** [comment]
@cagix Bei den MC-Fragen war uns ein Problem aufgefallen, denn die MC-Antworten durften jeweils nicht länger als 40 Zeichen sein, weil sie dann umgebrochen wurden und mehrzeilig waren. Dadurch wurden neue Objekte angelegt, u. a. neue String-Objekte, die aber nun gesplittet sind. Dadurch war es nicht mehr möglich, festzustellen, welche Antworten vom Benutzer ausgewählt wurden.

Deshalb hatten wir auch eine ursprüngliche Frage gegen eine andere ausgetauscht.

Ich denke, das liegt an den Quiz-Sachen.

**Comment by cagix** [comment]
> @cagix Bei den MC-Fragen war uns ein Problem aufgefallen, denn die MC-Antworten durften jeweils nicht länger als 40 Zeichen sein, weil sie dann umgebrochen wurden und mehrzeilig waren. Dadurch wurden neue Objekte angelegt, u. a. neue String-Objekte, die aber nun gesplittet sind. Dadurch war es nicht mehr möglich, festzustellen, welche Antworten vom Benutzer ausgewählt wurden.
> 
> 
> 
> Deshalb hatten wir auch eine ursprüngliche Frage gegen eine andere ausgetauscht.
> 
> 
> 
> Ich denke, das liegt an den Quiz-Sachen.

was genau möchtest du mir damit sagen?

aus meiner sicht ist die als richtig hinterlegte option einfach nicht korrekt, eine der anderen optionen passt zur frage. da muss vermutlich nur ein index angepasst werden.

**Comment by tgrothe** [comment]
> > @cagix Bei den MC-Fragen war uns ein Problem aufgefallen, denn die MC-Antworten durften jeweils nicht länger als 40 Zeichen sein, weil sie dann umgebrochen wurden und mehrzeilig waren. Dadurch wurden neue Objekte angelegt, u. a. neue String-Objekte, die aber nun gesplittet sind. Dadurch war es nicht mehr möglich, festzustellen, welche Antworten vom Benutzer ausgewählt wurden.
> > Deshalb hatten wir auch eine ursprüngliche Frage gegen eine andere ausgetauscht.
> > Ich denke, das liegt an den Quiz-Sachen.
> 
> was genau möchtest du mir damit sagen?
> 
> aus meiner sicht ist die als richtig hinterlegte option einfach nicht korrekt, eine der anderen optionen passt zur frage. da muss vermutlich nur ein index angepasst werden.

hm, dass da im prinzip ein bug ist, den wir aber mit einem workaround umgangen haben.

ich verbessere die falsche antwort und frage gerade selber.

**Comment by cagix** [comment]
wenn da ein bug ist und ihr den gesehen habt, wo ist die fehlermeldung?

**Comment by tgrothe** [comment]
> wenn da ein bug ist und ihr den gesehen habt, wo ist die fehlermeldung?

man kann nicht ermitteln oder feststellen, welche antwort(en) der benutzer ausgewählt hatte, wenn die antworten länger als 40 zeichen sind.

ich hatte noch kein ticket/issue dazu erstellt, das hatte ich irgendwie versäumt. bis morgen.
