### ISSUE TITLE
Dojo: Level 2, Pattern-Abfrage: Bitte noch mehr Beispiele

### ISSUE THREAD

**Issue by cagix** [Dungeon-CampusMinden/Dungeon#1513]
Aktuell gibt es zwei Pattern und je ein Beispiel (UML). 

Es wäre toll, wenn es mind. noch jeweils ein anderes Beispiel zu diesen Pattern geben würde. 

Es wäre auch super, wenn es noch ein Beispiel zu anderen Pattern (wie Strategy o.ä.) geben würde. 

Es wäre noch superer(?? 🫣), wenn es noch Beispiele geben würde, die nicht direkt zu einem Pattern passen.

**Comment by tgrothe** [comment]
> Es wäre noch superer(?? 🫣), wenn es noch Beispiele geben würde, die nicht direkt zu einem Pattern passen.

Sprich, wenn es ein Pattern-Beispiel ist, das gar keinem gängigen Entwurfsmuster entspricht, bitte "kein Pattern" (oder Ähnliches) eingeben? Finde ich gut 😉

**Comment by cagix** [comment]
ja, und noch weitere beispiele für visitor und observer. im moment ist die aufgabe etwas ... "karg".
