### ISSUE TITLE
Dojo: Level 2, MyImp: Gestaltung des Vorgabe-Codes

### ISSUE THREAD

**Issue by cagix** [Dungeon-CampusMinden/Dungeon#1515]
Für Level 2, Raum 3 ist der `MyImp` in `dojo.monster` vorgegeben. 

Ein paar Fragen und Gedanken:

1. Brauchen wir die Sammel-Methode `modifyMyImp` wirklich oder könnte die weg? Wenn man die weglassen könnte, dann wäre nur noch die eine ausimplementierte Methode `createEntity` übrig plus die kleinen von den Studis zu implementierenden Methoden. Das fände ich vorteilhaft.

2. Ich würde am liebsten `createEntity` ebenfalls aus `MyImp` auslagern, damit die Studis dort nicht versehentlich (oder absichtlich) herumeditieren. Wäre das denkbar? Damit steigt auch das Schwierigkeitslevel etwas an, da man nun nicht einfach nur passende Zeilen aus `createEntity` runterkopieren und leicht anpassen kann, sondern nachdenken muss. (Ich werde noch die HowToDungeon-Lecture anpassen und neu bereitstellen und dort die `VelocityComponent` sowie die `HealthComponent` und ggf. das `InventoryComponent` in einem anderen Kontext besprechen. Die `ItemPotionHealth` sollten die Studis trotz des besch**erten Namens von selbst finden, oder?) 

3. Können die von den Studis zu implementierenden Methoden bitte (a) ein dickes "TODO" im Javadoc bekommen (also "`TODO: <alter text>`"), und (b) der Schwierigkeit nach sortiert werden (`toggleImpGodMode`, `decreaseImpHealthTo25`, `setImpMoveable`, `addPotionHealthToInventory`)? Die neue Reihenfolge müsste sich auch im Text vom Imp spiegeln.

4. Die Wirkung der Implementierung der von den Studierenden zu befüllenden Methoden zeigt sich bis auf bei `addPotionHealthToInventory` live im Spiel, d.h. man sieht den Imp sich dann schnell/langsam bewegen bzw. sieht ihn Schaden nehmen etc. Aber die HealthPotion ist nicht im Spiel für den Spieler sichtbar, was mich stört - hier könnte man dann nämlich auch einfach ein beliebiges anderes Item reintun und es würde nix passieren, oder? Könnte man stattdessen dem Spieler eine HealthPotion ins Inventar setzen lassen? Das hätte dann tatsächlich Mehrwert ... Oder dem Imp ein Kampfsystem geben (wobei das vermutlich wieder zu weit geht, weil ich den "AI"-Kram gar nicht besprechen wollte)?

5. Namen der Methoden:
    - `decreaseImpHealthTo25`: Im Javadoc steht "Sets the health of MyImp to 25." -> sollte die Methode dann nicht auch `setImpHealthTo25` heissen?
    - `toggleImpGodMode`: Im Javadoc steht "Sets the god mode of MyImp to false." -> sollte die Methode dann nicht auch `disableImpGodMode` heissen?
    - `setImpMoveable`: Im Javadoc steht "Makes MyImp moveable (increases its speed)." -> sollte die Methode dann nicht auch `makeImpMoveable` oder `increaseImpSpeed` heissen?
    - `addPotionHealthToInventory`: Im Javadoc steht "Modifies the inventory of MyImp." -> sollte dort dann nicht "Add new HealthPotion to MyImp's inventory." stehen? 
    - Muss in den Methodennamen der String "Imp" vorkommen? Falls ja, dann bitte in allen von den Studis zu implementierenden Methoden. Ich bin eher für "nein", weil der Parameter ja eine beliebige `Entity` sein kann (bzw. vom Typ her ist). Dito sollte der Parametername auch angepasst werden.

---

Ich markiere das absichtlich nicht als https://github.com/Dungeon-CampusMinden/Dungeon/labels/bug, weil nichts im echten Sinne kaputt ist. Nur eben noch unterhalb der Qualitäts-Minimalschwelle, ab der ich das an die Studis ranlassen möchte. Also eine Art Qualitätsbug ;)

**Comment by tgrothe** [comment]
Deine Vorschläge klingen für mich alle gut. Ich oder @Denniso3 oder @JudiTeller können das ja, nachdem #1512 zu ist, umsetzen, wobei ich nicht schon wieder "vorgreifen" möchte ... Ich weiß nicht, ob das sehr eilt.
