### ISSUE TITLE
Dojo: Level 2, Pattern-Abfrage, zufällige Reihenfolge der Fragen

### ISSUE THREAD

**Issue by tgrothe** [Dungeon-CampusMinden/Dungeon#1518]
Die Fragen werden zurzeit immer in der gleichen Reihenfolge gestellt.

Damit der Lernerfolg höher ist, sollten die Fragen in zufälliger Reihenfolge gestellt werden, und die Fragen sollten möglichst nicht doppelt gestellt werden.

**Comment by cagix** [comment]
@tgrothe keine vernünftige summary, kein text im ersten kommentar? du solltest den drill nun wirklich langsam kennen 🤯

**Comment by cagix** [comment]
@tgrothe es reicht, aus den fragen zufällig auszuwählen und einfach nur dafür sorgen, dass beim neu würfeln nicht der selbe fragenindex von eben nochmal genommen wird. 

das reicht, und mehr möchte ich an dieser stelle nicht. damit ist dieser punkt für mich beendet, bitte investiere keine zeit in überkomplexe "lösungen" rein.

**Comment by tgrothe** [comment]
Ok, danke ... Ich passe die Beschreibungen noch an und werde das ohne eine überkomplexe Lösung umsetzen.

**Comment by cagix** [comment]
> Ok, danke ... Ich passe die Beschreibungen noch an 

wenn du schon ein neues ticket aufmachst, dann bitte immer direkt gleich titel plus beschreibung. die zeit mit zig-tausend markertickets ist definitiv vorbei. 

und den dialog hatten wir nun auch schon mehr als einmal. wenn mir sowas in zukunft wieder auffällt, werde ich die dinger direkt schließen. 

> und werde das ohne eine überkomplexe Lösung umsetzen.

danke.

**Comment by tgrothe** [comment]
> > Ok, danke ... Ich passe die Beschreibungen noch an
> 
> wenn du schon ein neues ticket aufmachst, dann bitte immer direkt gleich titel plus beschreibung. die zeit mit zig-tausend markertickets ist definitiv vorbei.
> 
> und den dialog hatten wir nun auch schon mehr als einmal. wenn mir sowas in zukunft wieder auffällt, werde ich die dinger direkt schließen.
> 
> > und werde das ohne eine überkomplexe Lösung umsetzen.
> 
> danke.

Ich habe nun alle Beschreibungen angepasst.
