### ISSUE TITLE
Dojo: Compiler/todo-assets: Übersetzte Dateien nicht in dem temporären Ordner ablegen

### ISSUE THREAD

**Issue by tgrothe** [Dungeon-CampusMinden/Dungeon#1531]
Für die Studis könnte es vielleicht verwirrend sein, wenn die `.class`-Dateien der `todo-assets` ganz woanders abgelegt werden. Und zum Beispiel IJ kommt damit auch gelegentlich durcheinander, bzw. versucht dann, diese zu öffnen.

Ich würde vorschlagen, die `.class`-Dateien im selben Ordner wie die `.java`-Datei abzulegen.

Das betrifft: `Cuboid.java`, `FehlerhafteKlasse.java` und `todo-assets/Implement_MyMonster/Monster.java`.

**Comment by tgrothe** [comment]
Und der Inhalt der `.java`-Dateien wird bislang noch einmal in einem Zwischenschritt in die temporären Dateien kopiert... Das sollte vielleicht auch geändert werden.

@cagix?

**Comment by tgrothe** [comment]
Bei mir landen die zurzeit unter `%appdata%` bzw. `C:\Users\<...>\AppData\Local\Temp` und es wird jedes Mal ein eigener Ordner angelegt:

![grafik](https://github.com/Dungeon-CampusMinden/Dungeon/assets/85501570/43572ae4-8221-474a-b42e-edfb597da639)

Dort räumt doch eigentlich auch selten jemand auf...

> Wo werden die denn aktuell hingelegt? Irgendwo unter "build/"? Ich finde, da gehört das auch hin.

Ich glaube, das würde IJ auch durcheinanderbringen...

**Comment by cagix** [comment]
@tgrothe Was Du da grad auftust, klingt nach einer ziemlichen Baustelle. Ich frage mich grad, ob sich das wirklich lohnt? Zumal die betreffenden Aufgaben realistisch betrachtet doch irgendwie ... künstlich und auch recht einfach sind und ich keine Idee habe, wie ich das in Zukunft mal spannender gestalten kann. 

Ich denke, ich würde das in dieser Iteration jetzt so lassen. In der nächsten Iteration sollten diese "todo-assets/" wieder verschwinden und durch "richtige" Klassen ersetzt werden, die auch in der IDE mitlaufen und eben nach "build/" übersetzt und vom normalen Classloader geladen werden. In diesen Klassen gibt es dann eine Menge leere Methoden, die einfach nix machen oder eine Exception werfen und die die Studis bearbeiten müssen. Es reicht ja, wenn sie im Spiel einen Hinweis bekommen, dann in die IDE gehen und den Code suchen und fixen/ergänzen und dann das Spiel nochmal neu starten. Schau Dir mal die [letzte Aufgabe](https://github.com/Programmiermethoden-CampusMinden/Prog2-Lecture/blob/master/homework/b04.md#a043-devdungeon-zerbrechende-tiles-und-speed-potions-50) auf Blatt 04 an, da ist das genau so gemacht. Das war auch etwa das, was ich mir vorgestellt hatte. Ich würde hier echt keine Zeit reinstecken an dieser Stelle.

**Comment by tgrothe** [comment]
> die auch in der IDE mitlaufen und eben nach "build/" übersetzt und vom normalen Classloader geladen werden. In diesen Klassen gibt es dann eine Menge leere Methoden, [...]

Das war auch so ein bisschen meine Idee, allerdings werden diese Klassen ja dann vom Build-Tool aufgegriffen und dürfen nicht "nicht übersetzbar" sein. ;)

Aber gut, ich sehe schon, die Baustelle würde größer werden, und ich investiere erst mal keine Energie darin ...

> Schau Dir mal die [letzte Aufgabe](https://github.com/Programmiermethoden-CampusMinden/Prog2-Lecture/blob/master/homework/b04.md#a043-devdungeon-zerbrechende-tiles-und-speed-potions-50) auf Blatt 04 an, da ist das genau so gemacht. Das war auch etwa das, was ich mir vorgestellt hatte.

Ich schaue's mir bis nächste Woche an ... danke erst mal. :)
