### ISSUE TITLE
Refactoring der entityStream-Methoden

### ISSUE THREAD

**Issue by cagix** [Dungeon-CampusMinden/Dungeon#1553]
Aus `AISystem`: 

```java
public AISystem() {
 super(AIComponent.class);
}

public void execute() {
 entityStream().forEach(this::executeAI);
}
```

Mit der Methode `System#entityStream` wird über alle **gefilterten** Entitäten iteriert. Der entsprechende Filter wird im Konstruktor gesetzt und ist recht weit weg vom Aufruf ... 

Intern speichern und aktualisieren die `EntitySystemMapper` passende Listen mit Entitäten, damit nicht in jedem Frame immer wieder jedes System über alle Entitäten laufen und filtern muss. Das sollte die Rechenlast deutlich verbessern, insbesondere wenn man #1381 weiter denkt und alle Tiles zu Entitäten macht.

Ein erster Schritt wäre vielleicht, die Methode von `entityStream` umzubenennen zu `filteredEntityStream`. Das löst das Problem mit dem "aus den Augen aus dem Sinn" noch nicht, aber zumindest wird hier deutlich gemacht, dass nach irgendwas gefiltert wird. Noch besser wäre es, wenn man die Filterbedingung nochmal als Parameter mitgeben würde - aber wie würde das dann technisch umsetzbar sein?

**Comment by AMatutat** [comment]
> Noch besser wäre es, wenn man die Filterbedingung nochmal als Parameter mitgeben würde - aber wie würde das dann technisch umsetzbar sein?


In `System` 

aus 

``` java
  public final Stream<Entity> entityStream() {
    return Game.entityStream(this);
  }
```


ein 
``` java
  public final Stream<Entity> entityStream(Set<Class<? extends Component>> filterRules) {
    return Game.entityStream(filterRules);
  }
```

machen.







Im Hintergrund passiert nämlich:

```java
  /**
   * Use this stream if you want to iterate over all entities that contain the given components.
   *
   * @param filter Set of Component classes that define the filter rules.
   * @return a stream of all entities currently in the game that contains the given components.
   */
  public static Stream<Entity> entityStream(Set<Class<? extends Component>> filter) {
    Stream<Entity> returnStream;
    Optional<EntitySystemMapper> rf =
        activeEntityStorage.stream().filter(f -> f.equals(filter)).findFirst();

    if (rf.isEmpty()) {
      EntitySystemMapper newMapper = createNewEntitySystemMapper(filter);
      returnStream = newMapper.stream();
    } else returnStream = rf.get().stream();
    return returnStream;
  }
  
```
