### ISSUE TITLE
DevDungeon: Indexfehler bei Brückentroll (RegExp)

### ISSUE THREAD

**Issue by cagix** [Dungeon-CampusMinden/Dungeon#1573]
Bei der RegExp-Frage des Brückentrolls zu "Zeile, die mit dem selben Wort beginnt und ended" wird der Ausdruck `^\b.*\b$` als korrekt bewertet. Es sollte aber `^(\w+).*\1$` sein ...

<img width="293" alt="Screenshot 2024-07-03 at 10 11 21" src="https://github.com/Programmiermethoden-CampusMinden/Prog2-Lecture/assets/20356276/19d24214-edf9-4940-aa7f-de81e182f983">

---

(erst nach dem mergen des devdungeons zu bearbeiten)

**Comment by Flamtky** [comment]
Habe das schonmal lokal bei mir korrigiert. Das kommt dann zusammen mit dem DevDungeon PR.
Zusätzlich habe ich noch 2 weitere Fragen angepasst die zwei richtige Antworten zur Auswahl hatten.

**Comment by cagix** [comment]
super. kannst dann bitte in dem pr dieses ticket referenzieren?
