### ISSUE TITLE
Game: Warum kann das Game.currentLevel() null sein im laufenden Spiel?

### ISSUE THREAD

**Issue by cagix** [Dungeon-CampusMinden/Dungeon#1575]
@AMatutat Ich bin grad am Analysieren des `PositionSystem` und bin über den Code in `randomPosition` gestolpert:

https://github.com/Dungeon-CampusMinden/Dungeon/blob/8658b688393298a73fc4ef70cc213a218a961754/game/src/core/systems/PositionSystem.java#L46-L48

Eine neue zufällige Position wird nur berechnet, wenn das aktuelle Level nicht `null` ist. 

Irgendwie irritiert mich das auf mehreren Ebenen:

- Semantisch: Wenn das PositionSystem läuft und für eine Entität eine neue zufällige Position berechnen will/soll, dann müsste es nach meinem Verständnis doch auch ein aktuelles Level geben? Sonst würde doch das ganze PositionSystem an der Stelle keinen Sinn ergeben?
- Semantisch: Wenn das Spiel läuft und das PositionSystem arbeitet und ich kein aktuelles Level habe - ist das nicht ein Fehler, d.h. müsste dann nicht das Spiel abgebrochen werden?
- Technisch: Warum muss ich mich als User (in diesem Fall das PositionSystem) darum kümmern, ob ich ein Level habe oder nicht? Sollte das nicht in `Game#randomTile` berücksichtigt werden?
- Technisch: Warum muss ich mich darum kümmern, dass das Tile frei ist? Könnte/sollte es nicht analog zu `Game#randomTile` auch ein `Game#randomFreeTile` geben?

Vermutlich stecken da eine ganze Menge Überlegungen dahinter, die für mich nicht transparent sind. Kannst Du dazu was sagen? 

---

Edit: Nebenfrage: Wenn die zufällige neue Position bereits belegt ist, wird eine neue Position durch rekursiven Aufruf gesucht. Prinzipiell finde ich Rekursion super - aber hier habe ich keinen "Anker", d.h. ich habe kein Element, welches in jedem Aufruf kleiner wird und so irgendwann zum Abbruch führt. Wäre es nicht wesentlich sinnvoller, von der initialen zufälligen neuen Position aus mit Breitensuche nach einer Kachel zu suchen, die noch nicht belegt ist?

---

Edit: Nebenfrage: In `ILevel` wird in `randomTile` ein zufälliges Tile der gewünschten Art geliefert oder `null`, falls es keine solche gibt. Ist das ein Fehlerzustand, d.h. sollte hier eigentlich eine Exception geworfen werden? Oder ist der Ausgang dieses Methodenaufrufs einfach nur unsicher, d.h. hier sollte eigentlich ein `Optional<Tile>` zurückgeliefert werden?

**Comment by AMatutat** [comment]
`currentLevel` kann genau durch zwei Situationen `null` sein.
1. Der Entwickler schreibt irgendwo ein `currentLevel = null;` und dann bist du selbst schuld, ist mir egal.
2. Zu Beginn des Spiels. Das `LevelSystem` lädt das Level, und solange es das nicht getan hat, ist `currentLevel` halt `null`. Unsere Systeme haben keine Rangordnung, daher weiß ich nicht, ob zuerst das `PositionSystem` oder das `LevelSystem` ausgeführt wird.
2a. Auch wenn ich es jetzt nicht weiß, ggf. schützt es auch noch beim manuellen Setzen von Leveln durch das DSL-Quest-Dungeon (ist jetzt aber eine wilde Unterstellung).

> Technisch: Warum muss ich mich als User (in diesem Fall das PositionSystem) darum kümmern, ob ich ein Level habe oder nicht? Sollte das nicht in Game#randomTile berücksichtigt werden?

Fair point. Ich würde jetzt sagen: Ein `null` Level ist eine Anomalie, die nur hier "beabsichtigt" ist. Daher spare ich mir an anderen Stellen den null-Check. Falls das Level an anderen Stellen null ist, soll das Spiel explodieren.

> Technisch: Warum muss ich mich darum kümmern, dass das Tile frei ist? Könnte/sollte es nicht analog zu Game#randomTile auch ein Game#randomFreeTile geben?

Hat bisher niemand angefragt. Die Unterscheidung zwischen Free-Tile und 'besetztem' Tile ist eher Game-Design und weniger technisch. In diesem konkreten Fall wollte ich nur nicht alle Monster zufällig auf die gleiche Startposition setzen.


> Edit: Nebenfrage: Wenn die zufällige neue Position bereits belegt ist, wird eine neue Position durch rekursiven Aufruf gesucht. Prinzipiell finde ich Rekursion super - aber hier habe ich keinen "Anker", d.h. ich habe kein Element, welches in jedem Aufruf kleiner wird und so irgendwann zum Abbruch führt. Wäre es nicht wesentlich sinnvoller, von der initialen zufälligen neuen Position aus mit Breitensuche nach einer Kachel zu suchen, die noch nicht belegt ist?

Auf dem Papier ja, theoretisch ist das hier eine potenzielle Endlosschleife (hatten wir schon mal irgendwo...). In der Praxis gibt es genug Platz für die Monster. Eine Breitensuche wäre technisch und theoretisch "korrekter", würde die Laufzeit aber nach oben treiben.


> Edit: Nebenfrage: In ILevel wird in randomTile ein zufälliges Tile der gewünschten Art geliefert oder null, falls es keine solche gibt. Ist das ein Fehlerzustand, d.h. sollte hier eigentlich eine Exception geworfen werden? Oder ist der Ausgang dieses Methodenaufrufs einfach nur unsicher, d.h. hier sollte eigentlich ein Optional<Tile> zurückgeliefert werden?

Should be `Optional<Tile>`

**Comment by AMatutat** [comment]
ToDo

- [ ] Dokumentation/Javadoc anpassen
- [ ] `Tile randomTile` -> `Optional <Tile> randomTile` 
- [ ] Endlos-Rekusion fixen (Breitensuche?)

**Comment by cagix** [comment]
> `currentLevel` kann genau durch zwei Situationen `null` sein.
> 
> 1. Der Entwickler schreibt irgendwo ein `currentLevel = null;` und dann bist du selbst schuld, ist mir egal.
> 2. Zu Beginn des Spiels. Das `LevelSystem` lädt das Level, und solange es das nicht getan hat, ist `currentLevel` halt `null`. Unsere Systeme haben keine Rangordnung, daher weiß ich nicht, ob zuerst das `PositionSystem` oder das `LevelSystem` ausgeführt wird. Durch den if-Check überspringe ich daher quasi einen loop-Durchgang des PositionSystem, wenn es vor dem LevelSystem ausgeführt wird.

ah, jetzt verstehe ich den hintergrund (besser).

wenn ich über die gesamtarchitektur nachdenke, scheinen wir eine art initialisierungsphase und eine art "normaler betrieb"-phase zu haben. aktuell ist das vermischt, d.h. wir werfen einfach alle systeme ins game und sagen "los". wenn wir das trennen würden, dann wäre im normalbetrieb der fall "kein level" definitiv ein fehlerzustand und ein grund, aus dem game auszusteigen. und man müsste den code für diese null-prüfungen nicht permanent mitschleppen.


> > Technisch: Warum muss ich mich als User (in diesem Fall das PositionSystem) darum kümmern, ob ich ein Level habe oder nicht? Sollte das nicht in Game#randomTile berücksichtigt werden?
> 
> Fair point. Ich würde jetzt sagen: Ein `null` Level ist eine Anomalie, die nur hier "beabsichtigt" ist. Daher spare ich mir an anderen Stellen den null-Check. Falls das Level an anderen Stellen null ist, soll das Spiel explodieren.

praktisch gesehen stimme ich dir zu.

von der aufgabenteilung her würde ich die verwaltung des levels eher bei game sehen - wenn mir Game#randomTile (vermutlich intern weitergeleitet an Level#randomTile) nichts liefern kann, dann würde ich als positionsystem einfach nichts tun (so wie jetzt, wenn das level null ist). aber ich sehe die prüfung, warum ich kein randomTile kriege, irgendwie nicht so richtig im aufgabenbereich vom positionsystem? 

oder anders herum: ich sehe irgendwie (noch) nicht so richtig ein, dass ich als positionsystem mich um den zustand des levels kümmern muss :)


> 
> > Technisch: Warum muss ich mich darum kümmern, dass das Tile frei ist? Könnte/sollte es nicht analog zu Game#randomTile auch ein Game#randomFreeTile geben?
> 
> Hat bisher niemand angefragt. Die Unterscheidung zwischen Free-Tile und 'besetztem' Tile ist eher Game-Design und weniger technisch. In diesem konkreten Fall wollte ich nur nicht alle Monster zufällig auf die gleiche Startposition setzen.

wir haben an anderen stellen auch sowas vorgehalten: "gib mir ein x mit bestimmten eigenschaften". finde ich hier ebenfalls als sinnvolle abstraktion, zumal das den code im positionsystem deutlich vereinfacht.


> 
> > Edit: Nebenfrage: Wenn die zufällige neue Position bereits belegt ist, wird eine neue Position durch rekursiven Aufruf gesucht. Prinzipiell finde ich Rekursion super - aber hier habe ich keinen "Anker", d.h. ich habe kein Element, welches in jedem Aufruf kleiner wird und so irgendwann zum Abbruch führt. Wäre es nicht wesentlich sinnvoller, von der initialen zufälligen neuen Position aus mit Breitensuche nach einer Kachel zu suchen, die noch nicht belegt ist?
> 
> Auf dem Papier ja, theoretisch ist das hier eine potenzielle Endlosschleife (hatten wir schon mal irgendwo...). In der Praxis gibt es genug Platz für die Monster. Eine Breitensuche wäre technisch und theoretisch "korrekter", würde die Laufzeit aber nach oben treiben.

bei der laufzeit weiss ich nicht. wenn wir zwei extremfälle betrachten:

- das level ist außer dem aktuellen tile komplett leer: dann baut die breitensuche eine queue mit den umliegenden 4 tiles auf und findet direkt im ersten schritt eine lösung. die zufallsbasierte methode könnte dagegen zufällig das aktuelle tile finden und müsste dann nochmal suchen.
- das level ist komplett voll, d.h. alle tiles sind belegt. hier muss die breitensuche tatsächlich alle tiles einmal in die queue aufnehmen - aber danach weisst du mit sicherheit, dass es kein freies tile gibt. die zufallsbasierte lösung kann diese aussage nicht treffen und würde endlos arbeiten (müssen).

im normalfall sollte die breitensuche ebenfalls nicht mehr aufwand bedeuten: man sucht gezielt in der nachbarschaft und bricht beim ersten gefundenen leeren feld ab. die zufallsbasierte methode könnte dagegen immer wieder eine belegte kachel finden und muss neu suchen.

oder andersherum gesagt: eigentlich spricht in diesem use-case alles für eine breitensuche und nichts für eine zufallsbasierte suche :)

**Comment by AMatutat** [comment]
> ah, jetzt verstehe ich den hintergrund (besser).

> wenn ich über die gesamtarchitektur nachdenke, scheinen wir eine art initialisierungsphase und eine art "normaler betrieb"-phase zu haben. aktuell ist das vermischt, d.h. wir werfen einfach alle systeme ins game und sagen "los". wenn wir das trennen würden, dann wäre im normalbetrieb der fall "kein level" definitiv ein fehlerzustand und ein grund, aus dem game auszusteigen. und man müsste den code für diese null-prüfungen nicht permanent mitschleppen.

man könnte im `Game#onSetup()` ggf. einfach schon ein Level ertellen und setzen, aber dann machst du die arbeit des Systems nochmal manuell.... 
In meinen Augen scheint es auch nur dieses System zu betreffen.
