### ISSUE TITLE
Orga: Zugriffsberechtigungen aufräumen

### ISSUE THREAD

**Issue by cagix** [Dungeon-CampusMinden/Dungeon#1577]
Das Semester ist (nahezu) durch - Zeit zum Aufräumen: Wer braucht wirklich einen Seat in der Organisation, d.h. wer braucht direkten Zugriff in einer bestimmten Rolle? Alle anderen sollten wieder als Member entfernt werden.

**Comment by cagix** [comment]
done. 

@Flamtky @Ironeer @malt-r @mpeters4 @tgrothe  die seats sind irgendwie auf einmal begrenzt; weiss nicht, ob und was sich geändert hat. ich habe deshalb mal bei der membership aufgeräumt. das dungeon-repo ist public, d.h. ihr habt weiterhin zugriff auf eure beiträge. wenn ihr das gefühl habt, ihr braucht trotzdem internen zugriff, meldet euch bitte bei mir. danke für eure beiträge zum projekt!

**Comment by tgrothe** [comment]
Ich kann die offenen Pull-Requests (#1366) nicht mehr (direkt) bearbeiten:

> $ git push
remote: Permission to Dungeon-CampusMinden/Dungeon.git denied to tgrothe.
fatal: unable to access 'https://github.com/Dungeon-CampusMinden/Dungeon.git/': The requested URL returned error: 403
