### ISSUE TITLE
Add your project In LSP4IJ 

### ISSUE THREAD

**Issue by angelozerr** [Dungeon-CampusMinden/Dungeon#1656]
I have noticed that you are using LSP4IJ.  That's great!

Could you please create a PR to add your project in https://github.com/redhat-developer/lsp4ij/tree/main#who-is-using-lsp4ij

And if you like LSP4IJ please add a review in jetbrains marketplace to help us to promote LSP4IJ 

Thanks!

**Comment by cagix** [comment]
@angelozerr Thanks for reaching out. For now, LSP support for our Dungeon DSL is just an ongoing experimental study and not a deployable product. As exciting as that may be, I'm not sure if a listing in the LSP4IJ wiki or the JetBrains marketplace is really appropriate right now?

As there's nothing we can do here at the moment, I'll close the ticket for the time being. In order that we can come back to it later, I'm attaching the label ‘later’.

**Comment by angelozerr** [comment]
I undestand @cagix 

Thanks for your clarification.
